#!/bin/bash
DOCKER_POSTFIX=$(cat postfix)
TAG="latest"
echo $DOCKER_POSTFIX
sudo env TAG=$TAG DOCKER_POSTFIX=$DOCKER_POSTFIX  docker-compose down
sudo env TAG=$TAG DOCKER_POSTFIX=$DOCKER_POSTFIX  docker-compose rm
sudo env TAG=$TAG DOCKER_POSTFIX=$DOCKER_POSTFIX  docker-compose pull
if [ -e worker ]; then
    sudo env TAG=$TAG DOCKER_POSTFIX=$DOCKER_POSTFIX docker-compose up  dpnk-worker dpnk-beat
elif [ -e web ]; then
    sudo env TAG=$TAG DOCKER_POSTFIX=$DOCKER_POSTFIX docker-compose up  dpnk-web
else
    sudo env TAG=$TAG DOCKER_POSTFIX=$DOCKER_POSTFIX docker-compose up
fi
