# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160531101208 on 2017-01-26 15:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dpnk', '0049_auto_20170113_1552'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    state_operations = [
        migrations.CreateModel(
            name='TShirtSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Velikost trička')),
                ('order', models.PositiveIntegerField(default=0)),
                ('ship', models.BooleanField(default=True, verbose_name='Posílá se?')),
                ('available', models.BooleanField(default=True, help_text='Zobrazuje se v nabídce trik', verbose_name='Je dostupné?')),
                ('t_shirt_preview', models.FileField(blank=True, null=True, upload_to='t_shirt_preview', verbose_name='Náhled trika')),
                ('price', models.IntegerField(default=0, verbose_name='Cena')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpnk.Campaign', verbose_name='Kampaň')),
            ],
            options={
                'db_table': 't_shirt_delivery_tshirtsize',
                'verbose_name': 'Velikost trička',
                'verbose_name_plural': 'Velikosti trička',
                'ordering': ['order'],
            },
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
