# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160531101208 on 2017-01-30 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0050_move_models_to_t_shirt_delivery'),
        ('t_shirt_delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsidiaryBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_shirt_delivery.DeliveryBatch', verbose_name='Dávka objednávek')),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpnk.Subsidiary', verbose_name='Pobočka', null=True, blank=True)),
            ],
            options={
                'verbose_name': 'Krabice pro firmu',
                'verbose_name_plural': 'Krabice pro firmu',
            },
        ),
        migrations.CreateModel(
            name='TeamPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='t_shirt_delivery.SubsidiaryBox', verbose_name='Krabice')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpnk.Team', verbose_name='Tým', null=True, blank=True)),
            ],
            options={
                'verbose_name': 'týmový balíček',
                'verbose_name_plural': 'týmové balíčky',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tshirtsize',
            unique_together=set([('name', 'campaign')]),
        ),
        migrations.AddField(
            model_name='packagetransaction',
            name='team_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='t_shirt_delivery.TeamPackage', verbose_name='Týmový balíček'),
        ),
        migrations.AlterModelTable(
            name='deliverybatch',
            table="t_shirt_delivery_deliverybatch",
        ),
        migrations.AlterModelTable(
            name='packagetransaction',
            table="t_shirt_delivery_packagetransaction",
        ),
        migrations.AlterModelTable(
            name='tshirtsize',
            table="t_shirt_delivery_tshirtsize",
        ),
    ]
