# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160531101208 on 2017-02-02 10:10
from __future__ import unicode_literals

from django.db import migrations


def link_box_package(apps, schema_editor):
    SubsidiaryBox = apps.get_model("t_shirt_delivery", "SubsidiaryBox")
    TeamPackage = apps.get_model("t_shirt_delivery", "TeamPackage")
    PackageTransaction = apps.get_model("t_shirt_delivery", "PackageTransaction")

    for package in PackageTransaction.objects.all():
        if package.user_attendance.team is None:
            subsidiary = None
        else:
            subsidiary = package.user_attendance.team.subsidiary
        subsidiary_box = SubsidiaryBox.objects.create(
            delivery_batch=package.delivery_batch,
            subsidiary=subsidiary,
        )
        team_package = TeamPackage.objects.create(
            box=subsidiary_box,
            team=package.user_attendance.team,
        )
        package.team_package = team_package
        package.save()


class Migration(migrations.Migration):

    dependencies = [
        ('t_shirt_delivery', '0002_auto_20170130_0343'),
    ]

    operations = [
        migrations.RunPython(link_box_package)
    ]
