# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-14 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_shirt_delivery', '0004_auto_20170219_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirtsize',
            name='name_cs',
            field=models.CharField(max_length=40, null=True, verbose_name='Velikost trička'),
        ),
        migrations.AddField(
            model_name='tshirtsize',
            name='name_en',
            field=models.CharField(max_length=40, null=True, verbose_name='Velikost trička'),
        ),
    ]
