# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-14 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_shirt_delivery', '0006_auto_20170406_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tshirtsize',
            options={'ordering': ['campaign', 'order'], 'verbose_name': 'Velikost trička', 'verbose_name_plural': 'Velikosti trička'},
        ),
        migrations.AddField(
            model_name='subsidiarybox',
            name='carrier_identification',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Identifikace u dopravce'),
        ),
    ]
