# Generated by Django 2.0.1 on 2018-02-22 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('t_shirt_delivery', '0008_auto_20170514_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subsidiarybox',
            options={'ordering': ['id'], 'verbose_name': 'Krabice pro pobočku', 'verbose_name_plural': 'Krabice pro pobočky'},
        ),
        migrations.AlterModelOptions(
            name='tshirtsize',
            options={'ordering': ['order'], 'verbose_name': 'Velikost trička', 'verbose_name_plural': 'Velikosti trička'},
        ),
        migrations.AddField(
            model_name='tshirtsize',
            name='name_dsnkcs',
            field=models.CharField(max_length=40, null=True, verbose_name='Velikost trička'),
        ),
        migrations.AlterField(
            model_name='packagetransaction',
            name='t_shirt_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_shirt_delivery.TShirtSize', verbose_name='Velikost trička'),
        ),
        migrations.AlterField(
            model_name='packagetransaction',
            name='team_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_shirt_delivery.TeamPackage', verbose_name='Týmový balíček'),
        ),
        migrations.AlterField(
            model_name='subsidiarybox',
            name='dispatched',
            field=models.BooleanField(default=False, verbose_name='Krabice vyřízena'),
        ),
        migrations.AlterField(
            model_name='subsidiarybox',
            name='subsidiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dpnk.Subsidiary', verbose_name='Pobočka'),
        ),
        migrations.AlterField(
            model_name='teampackage',
            name='dispatched',
            field=models.BooleanField(default=False, verbose_name='Balíek vyřízen'),
        ),
        migrations.AlterField(
            model_name='teampackage',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dpnk.Team', verbose_name='Tým'),
        ),
    ]
