# Generated by Django 2.0.2 on 2018-03-23 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('t_shirt_delivery', '0009_auto_20180222_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagetransaction',
            name='team_package',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='t_shirt_delivery.TeamPackage', verbose_name='Týmový balíček'),
            preserve_default=False,
        ),
    ]
