# Generated by Django 2.0.4 on 2018-05-10 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('t_shirt_delivery', '0010_auto_20180323_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverybatch',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Krátká poznámka'),
        ),
        migrations.AlterField(
            model_name='subsidiarybox',
            name='dispatched',
            field=models.BooleanField(default=False, verbose_name='Krabice evidována u dopravce'),
        ),
        migrations.AlterField(
            model_name='subsidiarybox',
            name='subsidiary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dpnk.Subsidiary', verbose_name='Pobočka'),
        ),
    ]
