# Generated by Django 2.2.11 on 2020-05-01 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_shirt_delivery', '0015_tshirtsize_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverybatch',
            name='pickup_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Datum vyzvednutí'),
        ),
    ]
