# Generated by Django 2.2.28 on 2024-12-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_shirt_delivery', '0017_deliverybatch_wellpack_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirtsize',
            name='author',
            field=models.CharField(blank=True, default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=30, null=True, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='tshirtsize',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=512, null=True, verbose_name='Popis'),
        ),
        migrations.AddField(
            model_name='tshirtsize',
            name='material',
            field=models.CharField(blank=True, default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=40, null=True, verbose_name='Materiál'),
        ),
        migrations.AddField(
            model_name='tshirtsize',
            name='material_cs',
            field=models.CharField(blank=True, default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=40, null=True, verbose_name='Materiál'),
        ),
        migrations.AddField(
            model_name='tshirtsize',
            name='material_dsnkcs',
            field=models.CharField(blank=True, default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=40, null=True, verbose_name='Materiál'),
        ),
        migrations.AddField(
            model_name='tshirtsize',
            name='material_en',
            field=models.CharField(blank=True, default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=40, null=True, verbose_name='Materiál'),
        ),
        migrations.AddField(
            model_name='tshirtsize',
            name='name1',
            field=models.CharField(default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=40, verbose_name='Název trička'),
        ),
        migrations.AddField(
            model_name='tshirtsize',
            name='name1_cs',
            field=models.CharField(default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=40, null=True, verbose_name='Název trička'),
        ),
        migrations.AddField(
            model_name='tshirtsize',
            name='name1_dsnkcs',
            field=models.CharField(default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=40, null=True, verbose_name='Název trička'),
        ),
        migrations.AddField(
            model_name='tshirtsize',
            name='name1_en',
            field=models.CharField(default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=40, null=True, verbose_name='Název trička'),
        ),
        migrations.AddField(
            model_name='tshirtsize',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Muž'), ('female', 'Žena'), ('unisex', 'Vhodné pro obě pohlaví')], default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=10, null=True, verbose_name='Pohlaví'),
        ),
        migrations.AddField(
            model_name='tshirtsize',
            name='size',
            field=models.CharField(blank=True, default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=20, null=True, verbose_name='Velikost'),
        ),
        migrations.AddField(
            model_name='tshirtsize',
            name='t_shirt_preview_cs',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='t_shirt_preview', verbose_name='Náhled trika'),
        ),
        migrations.AddField(
            model_name='tshirtsize',
            name='t_shirt_preview_dsnkcs',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='t_shirt_preview', verbose_name='Náhled trika'),
        ),
        migrations.AddField(
            model_name='tshirtsize',
            name='t_shirt_preview_en',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='t_shirt_preview', verbose_name='Náhled trika'),
        ),
    ]
