# Generated by Django 2.2.28 on 2024-12-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_shirt_delivery', '0018_auto_20241211_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tshirtsize',
            name='t_shirt_preview_cs',
        ),
        migrations.RemoveField(
            model_name='tshirtsize',
            name='t_shirt_preview_dsnkcs',
        ),
        migrations.RemoveField(
            model_name='tshirtsize',
            name='t_shirt_preview_en',
        ),
        migrations.AddField(
            model_name='tshirtsize',
            name='description_cs',
            field=models.TextField(blank=True, default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=512, null=True, verbose_name='Popis'),
        ),
        migrations.AddField(
            model_name='tshirtsize',
            name='description_dsnkcs',
            field=models.TextField(blank=True, default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=512, null=True, verbose_name='Popis'),
        ),
        migrations.AddField(
            model_name='tshirtsize',
            name='description_en',
            field=models.TextField(blank=True, default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=512, null=True, verbose_name='Popis'),
        ),
    ]
