# Generated by Django 2.2.28 on 2024-12-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_shirt_delivery', '0019_auto_20241211_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirtsize',
            name='author',
            field=models.CharField(default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=30, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='tshirtsize',
            name='description',
            field=models.TextField(default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=512, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='tshirtsize',
            name='description_cs',
            field=models.TextField(default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=512, null=True, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='tshirtsize',
            name='description_dsnkcs',
            field=models.TextField(default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=512, null=True, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='tshirtsize',
            name='description_en',
            field=models.TextField(default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=512, null=True, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='tshirtsize',
            name='material',
            field=models.CharField(default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=40, verbose_name='Materiál'),
        ),
        migrations.AlterField(
            model_name='tshirtsize',
            name='material_cs',
            field=models.CharField(default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=40, null=True, verbose_name='Materiál'),
        ),
        migrations.AlterField(
            model_name='tshirtsize',
            name='material_dsnkcs',
            field=models.CharField(default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=40, null=True, verbose_name='Materiál'),
        ),
        migrations.AlterField(
            model_name='tshirtsize',
            name='material_en',
            field=models.CharField(default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=40, null=True, verbose_name='Materiál'),
        ),
        migrations.AlterField(
            model_name='tshirtsize',
            name='sex',
            field=models.CharField(blank=True, choices=[('', '---------'), ('male', 'Muž'), ('female', 'Žena'), ('unisex', 'Vhodné pro obě pohlaví')], default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=10, verbose_name='Pohlaví'),
        ),
        migrations.AlterField(
            model_name='tshirtsize',
            name='size',
            field=models.CharField(blank=True, default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=20, verbose_name='Velikost'),
        ),
    ]
