# Generated by Django 2.2.28 on 2024-12-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_shirt_delivery', '0020_auto_20241211_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tshirtsize',
            name='description_cs',
        ),
        migrations.RemoveField(
            model_name='tshirtsize',
            name='description_dsnkcs',
        ),
        migrations.RemoveField(
            model_name='tshirtsize',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='tshirtsize',
            name='material_cs',
        ),
        migrations.RemoveField(
            model_name='tshirtsize',
            name='material_dsnkcs',
        ),
        migrations.RemoveField(
            model_name='tshirtsize',
            name='material_en',
        ),
        migrations.AlterField(
            model_name='tshirtsize',
            name='author',
            field=models.CharField(blank=True, default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=30, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='tshirtsize',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=512, verbose_name='Popis'),
        ),
        migrations.AlterField(
            model_name='tshirtsize',
            name='material',
            field=models.CharField(blank=True, default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=40, verbose_name='Materiál'),
        ),
    ]
