# Generated by Django 2.2.28 on 2024-12-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_shirt_delivery', '0021_auto_20241211_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirtsize',
            name='description_cs',
            field=models.TextField(blank=True, default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=512, null=True, verbose_name='Popis'),
        ),
        migrations.AddField(
            model_name='tshirtsize',
            name='description_dsnkcs',
            field=models.TextField(blank=True, default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=512, null=True, verbose_name='Popis'),
        ),
        migrations.AddField(
            model_name='tshirtsize',
            name='description_en',
            field=models.TextField(blank=True, default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=512, null=True, verbose_name='Popis'),
        ),
        migrations.AddField(
            model_name='tshirtsize',
            name='material_cs',
            field=models.CharField(blank=True, default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=40, null=True, verbose_name='Materiál'),
        ),
        migrations.AddField(
            model_name='tshirtsize',
            name='material_dsnkcs',
            field=models.CharField(blank=True, default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=40, null=True, verbose_name='Materiál'),
        ),
        migrations.AddField(
            model_name='tshirtsize',
            name='material_en',
            field=models.CharField(blank=True, default='', help_text='Požadováno pro novou RTWBB frontend aplikaci', max_length=40, null=True, verbose_name='Materiál'),
        ),
    ]
