# Generated by Django 2.2.28 on 2025-03-04 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0187_add_box_request'),
        ('t_shirt_delivery', '0022_auto_20241211_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_requests', to='dpnk.CompanyAdmin')),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='box_requests', to='dpnk.Subsidiary', verbose_name='Pobočka')),
            ],
            options={
                'unique_together': {('company_admin', 'subsidiary')},
            },
        ),
    ]
