# Generated by Django 2.2.28 on 2026-03-02 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('t_shirt_delivery', '0023_add_box_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverybatch',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datum vytvoření'),
        ),
        migrations.AlterField(
            model_name='deliverybatch',
            name='pickup_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Datum vyzvednutí'),
        ),
    ]
