# Generated by Django 2.2.28 on 2026-03-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_shirt_delivery', '0024_auto_20260302_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidiarybox',
            name='status_code',
            field=models.PositiveIntegerField(null=True, verbose_name='Kód stavu'),
        ),
        migrations.AddField(
            model_name='subsidiarybox',
            name='status_datetime',
            field=models.DateTimeField(null=True, verbose_name='Datum stavu'),
        ),
        migrations.AddField(
            model_name='subsidiarybox',
            name='status_description',
            field=models.CharField(blank=True, max_length=355, null=True, verbose_name='Popis stavu'),
        ),
    ]
