# Generated by Django 2.2.28 on 2026-04-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_shirt_delivery', '0025_auto_20260302_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidiarybox',
            name='status_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Kód stavu'),
        ),
        migrations.AlterField(
            model_name='subsidiarybox',
            name='status_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datum stavu'),
        ),
    ]
