# Generated by Django 2.2.11 on 2020-05-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivation_messages', '0002_motivationmessage_campaign_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivationmessage',
            name='day_from',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ode dne'),
        ),
        migrations.AlterField(
            model_name='motivationmessage',
            name='day_to',
            field=models.IntegerField(blank=True, null=True, verbose_name='Do dne'),
        ),
    ]
