# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0002_auto_20160118_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirtsize',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Cena'),
        ),
    ]
