# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0009_auto_20160224_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='distance_from',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='distance_to',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='is_working_ride_from',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='is_working_ride_to',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_from',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_to',
        ),
        migrations.AlterField(
            model_name='gpxfile',
            name='trip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dpnk.Trip'),
        ),
    ]
