# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 17:02
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0012_auto_20160227_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userattendance',
            name='track',
        ),
        migrations.RenameField(
            model_name='userattendance',
            old_name='multi_track',
            new_name='track',
        ),
    ]
