# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0013_auto_20160227_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyadmin',
            options={'verbose_name': 'Koordinátor společnosti', 'verbose_name_plural': 'Koordinátoři společností'},
        ),
        migrations.AlterModelOptions(
            name='subsidiary',
            options={'verbose_name': 'Pobočka společnosti', 'verbose_name_plural': 'Pobočky společností'},
        ),
        migrations.AddField(
            model_name='companyadmin',
            name='will_pay_opt_in',
            field=models.BooleanField(default=False, verbose_name='Souhlas s platbou za zaměstnance.'),
        ),
        migrations.AlterField(
            model_name='cityincampaign',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cityincampaign', to='dpnk.City'),
        ),
        migrations.AlterField(
            model_name='companyadmin',
            name='administrated_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_admin', to='dpnk.Company', verbose_name='Koordinovaná společnost'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='competitor_type',
            field=models.CharField(choices=[('single_user', 'Jednotliví soutěžící'), ('liberos', 'Liberos'), ('team', 'Týmy'), ('company', 'Soutěž spoleností')], help_text='Určuje, zdali bude soutěž týmová, nebo pro jednotlivce. Ostatní volby vybírejte jen pokud víte, k čemu slouží.', max_length=16, verbose_name='Typ soutěžícího'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='user_attendance',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_trips', to='dpnk.UserAttendance'),
        ),
    ]
