# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0014_auto_20160302_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mailing_hash',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Hash poslední synchronizace s mailingem'),
        ),
    ]
