# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-05 17:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0015_auto_20160303_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='unapproved_member_count',
            field=models.IntegerField(db_index=True, default=None, editable=False, null=True, verbose_name='Počet neschválených členů týmu'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='distance',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)], verbose_name='Ujetá vzdálenost'),
        ),
    ]
