# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160321164524 on 2016-03-27 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0018_auto_20160327_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay_type',
            field=models.CharField(blank=True, choices=[('mp', 'mPenize - mBank'), ('kb', 'MojePlatba'), ('rf', 'ePlatby pro eKonto'), ('pg', 'GE Money Bank'), ('pv', 'Sberbank (Volksbank)'), ('pf', 'Fio banka'), ('cs', 'PLATBA 24 – Česká spořitelna'), ('era', 'Era - Poštovní spořitelna'), ('cb', 'ČSOB'), ('c', 'Kreditní karta přes GPE'), ('bt', 'bankovní převod'), ('pt', 'převod přes poštu'), ('sc', 'superCASH'), ('psc', 'PaySec'), ('mo', 'Mobito'), ('uc', 'UniCredit'), ('t', 'testovací platba'), ('fa', 'faktura mimo PayU'), ('fc', 'organizace platí fakturou'), ('am', 'člen Klubu přátel Auto*Matu'), ('amw', 'kandidát na členství v Klubu přátel Auto*Matu'), ('fe', 'neplatí startovné')], max_length=50, null=True, verbose_name='Typ platby'),
        ),
    ]
