# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160321164524 on 2016-03-28 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0019_auto_20160327_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyadmin',
            name='userprofile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_admin', to='dpnk.UserProfile', verbose_name='User profile'),
        ),
        migrations.AlterUniqueTogether(
            name='companyadmin',
            unique_together=set([('userprofile', 'campaign')]),
        ),
    ]
