# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160321164524 on 2016-03-28 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0021_auto_20160328_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyadmin',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_admin', to='dpnk.UserProfile', verbose_name='User profile'),
        ),
        migrations.RemoveField(
            model_name='companyadmin',
            name='user',
        ),
    ]
