# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160321164524 on 2016-04-07 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0023_userprofile_company_admin_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='late_admission_phase',
        ),
        migrations.AlterField(
            model_name='company',
            name='dic',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='DIČ'),
        ),
        migrations.AlterField(
            model_name='companyadmin',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_admin', to='dpnk.UserProfile', verbose_name='Uživatelský profil'),
        ),
    ]
