# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160321164524 on 2016-04-12 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0024_auto_20160407_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='cyklistesobe_slug',
            field=models.SlugField(max_length=40, null=True, verbose_name='Jméno skupiny na webu Cyklisté sobě'),
        ),
    ]
