# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160321164524 on 2016-05-01 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0026_auto_20160426_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='frequency',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='commute_mode',
            field=models.CharField(blank=True, choices=[('bicycle', 'Kolo'), ('by_foot', 'Chůze/běh'), ('by_other_vehicle', 'Jinak'), ('no_work', 'Nijak/vůbec')], default=None, max_length=20, null=True, verbose_name='Mód dopravy'),
        ),
    ]
