# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160321164524 on 2016-05-31 12:38
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0030_choice_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ('order',), 'verbose_name': 'Nabídka k anketním otázce', 'verbose_name_plural': 'Nabídky k anketním otázkám'},
        ),
        migrations.AddField(
            model_name='answer',
            name='comment_given',
            field=models.TextField(blank=True, null=True, verbose_name='Hodnotitelský komentář'),
        ),
        migrations.AlterField(
            model_name='gpxfile',
            name='track',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, geography=True, help_text='\n<ul>\n   <li><strong>Zadávání trasy zahájíte kliknutím na tlačítko "Nakreslit trasu", ukončíte kliknutím na cílový bod.</strong></li>\n   <li>Změnu trasy provedete po přepnutí do režimu úprav kliknutím na trasu.</li>\n   <li>Trasu stačí zadat tak, že bude zřejmé, kterými ulicemi vede.</li>\n   <li>Zadání přesnějšího průběhu nám však může pomoci lépe zjistit jak se lidé na kole pohybují.</li>\n   <li>Trasu bude možné změnit nebo upřesnit i později v průběhu soutěže.</li>\n   <li>Polohu začátku a konce trasy stačí zadávat s přesností 100m.</li>\n</ul>\nTrasa slouží k výpočtu vzdálenosti a pomůže nám lépe určit potřeby lidí pohybuících se ve městě na kole. Vaše cesta se zobrazí vašim týmovým kolegům.\n<br/>Trasy všech účastníků budou v anonymizované podobě zobrazené na úvodní stránce.\n', null=True, srid=4326, verbose_name='trasa'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ecc_email',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=128, unique=True, verbose_name='Email v ECC'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ecc_password',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=128, verbose_name='Heslo v ECC'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='type',
            field=models.CharField(choices=[('rekola', 'ReKola'), ('sportlife', 'SportLife')], default='rekola', max_length=10, verbose_name='typ voucheru'),
        ),
    ]
