# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160531101208 on 2016-08-22 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0037_auto_20160822_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='has_any_tshirt',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
