# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160531101208 on 2016-08-25 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0038_campaign_has_any_tshirt'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='language_prefixes',
            field=models.CharField(choices=[('dpnk', 'Do práce na kole'), ('dsnk', 'Do školy na kole')], default='', max_length=16, verbose_name='Jazyková sada'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='wp_api_url',
            field=models.URLField(blank=True, default='http://www.dopracenakole.cz/', null=True, verbose_name='Adresa pro Wordpress API se články'),
        ),
    ]
