# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160531101208 on 2016-08-25 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0039_auto_20160825_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='max_team_members',
            field=models.PositiveIntegerField(blank=True, default=5, null=True, verbose_name='Počet lidí v týmu'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='language_prefixes',
            field=models.CharField(choices=[('dpnk', 'Do práce na kole'), ('dsnk', 'Do školy na kole')], default='dpnk', max_length=16, verbose_name='Jazyková sada'),
        ),
    ]
