# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160531101208 on 2016-11-29 18:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0041_campaign_track_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True, verbose_name='token')),
                ('discount', models.PositiveIntegerField(default=100, verbose_name='sleva (v procentech)')),
                ('note', models.CharField(blank=True, max_length=50, null=True, verbose_name='poznámka')),
                ('receiver', models.CharField(blank=True, max_length=50, null=True, verbose_name='příjemce')),
                ('sent', models.BooleanField(default=False, verbose_name='Odeslaný')),
            ],
            options={
                'verbose_name': 'Slevový kupón',
                'verbose_name_plural': 'Slevové kupóny',
            },
        ),
        migrations.CreateModel(
            name='DiscountCouponType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='jméno typu voucheru')),
                ('prefix', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_prefix', message='Prefix musí sestávat pouze z velkých písmen', regex='^[A-Z]*$')], verbose_name='prefix')),
            ],
            options={
                'verbose_name': 'Typ slevového kupónu',
                'verbose_name_plural': 'Typy slevového kupónu',
            },
        ),
        migrations.AddField(
            model_name='discountcoupon',
            name='coupon_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dpnk.DiscountCouponType', verbose_name='typ voucheru'),
        ),
        migrations.AddField(
            model_name='discountcoupon',
            name='user_attendance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dpnk.UserAttendance'),
        ),
        migrations.AlterUniqueTogether(
            name='discountcoupon',
            unique_together=set([('token', 'coupon_type')]),
        ),
    ]
