# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160531101208 on 2016-12-12 18:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dpnk', '0042_auto_20161129_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcoupon',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discountcoupon_create', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='discountcoupon',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Datum vytvoření'),
        ),
        migrations.AddField(
            model_name='discountcoupon',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Datum poslední změny'),
        ),
        migrations.AddField(
            model_name='discountcoupon',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discountcoupon_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
    ]
