# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160531101208 on 2016-12-31 00:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0044_auto_20161219_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='type',
            new_name='competition_type',
        ),
        migrations.RenameField(
            model_name='phase',
            old_name='type',
            new_name='phase_type',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='type',
            new_name='question_type',
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='type',
            new_name='voucher_type',
        ),
        migrations.AlterUniqueTogether(
            name='phase',
            unique_together=set([('phase_type', 'campaign')]),
        ),
    ]
