# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160531101208 on 2017-01-06 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0045_auto_20161231_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidiary',
            name='city',
            field=models.ForeignKey(help_text="Rozhoduje o tom, do soutěží jakého města budete zařazenia kde budete dostávat ceny - vizte <a href='http://www.dopracenakole.cz/pravidla' target='_blank'>pravidla soutěže</a>", on_delete=django.db.models.deletion.CASCADE, to='dpnk.City', verbose_name='Spádové město'),
        ),
    ]
