# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160531101208 on 2017-01-06 18:46
from __future__ import unicode_literals

import datetime

from django.db import migrations
from django.db.models import ObjectDoesNotExist


def get_phase(campaign, phase_type):
    try:
        return campaign.phase_set.get(phase_type=phase_type)
    except ObjectDoesNotExist:
        return None


def remove_price_levels(apps, schema_editor):
    PriceLevel = apps.get_model("price_level", "PriceLevel")
    PriceLevel.objects.all().delete()


def make_price_levels(apps, schema_editor):
    PriceLevel = apps.get_model("price_level", "PriceLevel")
    Campaign = apps.get_model("dpnk", "Campaign")
    for c in Campaign.objects.all():
        registration_price_level = get_phase(c, 'registration')
        if registration_price_level:
            PriceLevel.objects.create(
                category='basic',
                price=c.admission_fee,
                pricable=c,
                name='Early price for individuals',
                takes_effect_on=registration_price_level.date_from or datetime.date(year=2000, month=1, day=1),
            )
            PriceLevel.objects.create(
                category='company',
                price=c.admission_fee_company,
                pricable=c,
                name='Early price for companies',
                takes_effect_on=registration_price_level.date_from or datetime.date(year=2000, month=1, day=1),
            )
        late_price_level = get_phase(c, 'late_admission')
        if late_price_level:
            PriceLevel.objects.create(
                category='basic',
                price=c.late_admission_fee,
                pricable=c,
                name='Late price for individuals',
                takes_effect_on=late_price_level.date_from or datetime.date(year=2000, month=1, day=1),
            )
            PriceLevel.objects.create(
                category='company',
                price=c.late_admission_fee_company,
                pricable=c,
                name='Late price for companies',
                takes_effect_on=late_price_level.date_from or datetime.date(year=2000, month=1, day=1),
            )


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0046_auto_20170106_1943'),
        ('price_level', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(make_price_levels, reverse_code=remove_price_levels),
    ]
