# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160531101208 on 2017-01-06 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0047_data_create_price_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='admission_fee',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='admission_fee_company',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='late_admission_fee',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='late_admission_fee_company',
        ),
    ]
