# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160531101208 on 2017-01-13 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0048_auto_20170106_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionresult',
            name='result',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, default=None, max_digits=10, null=True, verbose_name='Výsledek'),
        ),
    ]
