# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 17:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dpnk', '0048_auto_20151202_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxfile',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gpxfile_create', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='gpxfile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Datum vytvoření'),
        ),
        migrations.AddField(
            model_name='gpxfile',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Datum poslední změny'),
        ),
        migrations.AddField(
            model_name='gpxfile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gpxfile_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choicetype_set', to='dpnk.ChoiceType', verbose_name='Typ volby'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='company_competitors',
            field=models.ManyToManyField(blank=True, related_name='competitions', to='dpnk.Company', verbose_name='Přihlášené soutěžící firmy'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='team_competitors',
            field=models.ManyToManyField(blank=True, related_name='competitions', to='dpnk.Team', verbose_name='Přihlášené soutěžící týmy'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='user_attendance_competitors',
            field=models.ManyToManyField(blank=True, related_name='competitions', to='dpnk.UserAttendance', verbose_name='Přihlášení soutěžící jednotlivci'),
        ),
        migrations.AlterField(
            model_name='userattendance',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userattendance_set', to='dpnk.UserProfile', verbose_name='Uživatelský profil'),
        ),
    ]
