# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-01 21:49
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0061_auto_20170426_1949'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='answer',
            managers=[
                ('objectsvotable', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='enable_likes',
            field=models.BooleanField(default=False, verbose_name='Povolit likování příspěvků dotazníku'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='competition_type',
            field=models.CharField(choices=[('length_by_foot', 'Uběhnutá/ujdená vzdálenost'), ('length', 'Ujetá vzdálenost'), ('frequency', 'Pravidelnost jízd na kole'), ('questionnaire', 'Dotazník')], help_text='Určuje, zdali bude soutěž výkonnostní (na ujetou vzdálenost), nebo na pravidelnost. Volba "Dotazník" slouží pro kreativní soutěže, cyklozaměstnavatele roku a další dotazníky; je nutné definovat otázky.', max_length=16, verbose_name='Typ'),
        ),
        migrations.AlterField(
            model_name='gpxfile',
            name='track',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, geography=True, help_text='\n<ul>\n   <li><strong>Zadávání trasy zahájíte kliknutím na tlačítko <span style="display: inline-block;" class="leaflet-draw-toolbar leaflet-bar leaflet-draw-toolbar-top"><a class="leaflet-draw-draw-polyline" href="#"></a></span>.</strong></li>\n   <li>Další body zadáváte kliknutím do mapy, <strong>cílový bod zadáte dvouklikem.</strong></li>\n   <li>Změnu trasy provedete po přepnutí do režimu úprav (<span style="display: inline-block;" class="leaflet-draw-toolbar leaflet-bar"><a class="leaflet-draw-edit-edit" href="#"></a></span>) kliknutím na trasu.</li>\n   <li>Trasu stačí zadat tak, že bude zřejmé, kterými ulicemi vede.\n   (Zadání přesnějšího průběhu nám však může pomoci lépe zjistit, jak se lidé na kole pohybují.)</li>\n   <li>Trasu bude možné změnit nebo upřesnit i později v průběhu soutěže.\n   (Trasy za jednotlivé dny však jen 7 dní nazpět.)</li>\n   <li>Polohu začátku a konce trasy stačí zadávat se 100m přesností.</li>\n</ul>\nTrasa slouží k výpočtu vzdálenosti a pomůže nám lépe určit potřeby lidí pohybuících se ve městě na kole.\n<br/>Trasy všech účastníků budou v anonymizované podobě zobrazené na <a href="https://mapa.prahounakole.cz/?zoom=13&lat=50.08741&lon=14.4211&layers=_Wgt">mapě Prahou na kole</a>.\n', null=True, srid=4326, verbose_name='trasa'),
        ),
        migrations.AlterField(
            model_name='userattendance',
            name='track',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, geography=True, help_text='\n<ul>\n   <li><strong>Zadávání trasy zahájíte kliknutím na tlačítko <span style="display: inline-block;" class="leaflet-draw-toolbar leaflet-bar leaflet-draw-toolbar-top"><a class="leaflet-draw-draw-polyline" href="#"></a></span>.</strong></li>\n   <li>Další body zadáváte kliknutím do mapy, <strong>cílový bod zadáte dvouklikem.</strong></li>\n   <li>Změnu trasy provedete po přepnutí do režimu úprav (<span style="display: inline-block;" class="leaflet-draw-toolbar leaflet-bar"><a class="leaflet-draw-edit-edit" href="#"></a></span>) kliknutím na trasu.</li>\n   <li>Trasu stačí zadat tak, že bude zřejmé, kterými ulicemi vede.\n   (Zadání přesnějšího průběhu nám však může pomoci lépe zjistit, jak se lidé na kole pohybují.)</li>\n   <li>Trasu bude možné změnit nebo upřesnit i později v průběhu soutěže.\n   (Trasy za jednotlivé dny však jen 7 dní nazpět.)</li>\n   <li>Polohu začátku a konce trasy stačí zadávat se 100m přesností.</li>\n</ul>\nTrasa slouží k výpočtu vzdálenosti a pomůže nám lépe určit potřeby lidí pohybuících se ve městě na kole.\n<br/>Trasy všech účastníků budou v anonymizované podobě zobrazené na <a href="https://mapa.prahounakole.cz/?zoom=13&lat=50.08741&lon=14.4211&layers=_Wgt">mapě Prahou na kole</a>.\n', null=True, srid=4326, verbose_name='trasa'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age_group',
            field=models.PositiveIntegerField(blank=True, choices=[(2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980), (1979, 1979), (1978, 1978), (1977, 1977), (1976, 1976), (1975, 1975), (1974, 1974), (1973, 1973), (1972, 1972), (1971, 1971), (1970, 1970), (1969, 1969), (1968, 1968), (1967, 1967), (1966, 1966), (1965, 1965), (1964, 1964), (1963, 1963), (1962, 1962), (1961, 1961), (1960, 1960), (1959, 1959), (1958, 1958), (1957, 1957), (1956, 1956), (1955, 1955), (1954, 1954), (1953, 1953), (1952, 1952), (1951, 1951), (1950, 1950), (1949, 1949), (1948, 1948), (1947, 1947), (1946, 1946), (1945, 1945), (1944, 1944), (1943, 1943), (1942, 1942), (1941, 1941), (1940, 1940), (1939, 1939), (1938, 1938), (1937, 1937), (1936, 1936), (1935, 1935), (1934, 1934), (1933, 1933), (1932, 1932), (1931, 1931), (1930, 1930), (1929, 1929), (1928, 1928), (1927, 1927), (1926, 1926), (1925, 1925), (1924, 1924), (1923, 1923), (1922, 1922), (1921, 1921), (1920, 1920), (1919, 1919), (1918, 1918)], help_text='Nepovinné, slouží pouze pro účely statistky', null=True, verbose_name='Ročník narození'),
        ),
    ]
