# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0062_auto_20170501_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ico',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Pokud má vaše společnost IČO, prosím vyplňte, jinak nechte prázdné.', null=True, verbose_name='IČO'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_pdf',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='invoices', verbose_name='PDF faktury'),
        ),
    ]
