# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0063_auto_20170509_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionresult',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Datum vytvoření'),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Datum poslední změny'),
        ),
    ]
