# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 12:26
from __future__ import unicode_literals

from django.db import migrations, models


def populate_commute_modes(apps, schema_editor):
    GpxFile = apps.get_model("dpnk", "GpxFile")
    CommuteMode = apps.get_model("dpnk", "CommuteMode")

    for commute_mode in CommuteMode.objects.all():
        print(commute_mode.slug)
        GpxFile.objects.filter(
            commute_mode=commute_mode.slug,
        ).update(
            commute_mode_choice=commute_mode,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0070_gpxfile_commute_mode'),
    ]

    operations = [
        migrations.RunPython(populate_commute_modes),
    ]
