# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0071_gpxfile_commute_mode_populate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpxfile',
            name='commute_mode',
        ),
    ]
