# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import dpnk.models.competition


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0073_gpxfile_commute_mode_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='commute_modes',
            field=models.ManyToManyField(blank=True, default=dpnk.models.competition.default_commute_modes, to='dpnk.CommuteMode', verbose_name='Počítané módy dopravy'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='competition_type',
            field=models.CharField(choices=[('length', 'Výkonnost'), ('frequency', 'Pravidelnost'), ('questionnaire', 'Dotazník')], help_text='Určuje, zdali bude soutěž výkonnostní (na ujetou vzdálenost), nebo na pravidelnost. Volba "Dotazník" slouží pro kreativní soutěže, cyklozaměstnavatele roku a další dotazníky; je nutné definovat otázky.', max_length=16, verbose_name='Typ'),
        ),
    ]
