# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 19:46
from __future__ import unicode_literals

from django.db import migrations

import dpnk.models.competition


def set_default_commute_modes(apps, schema_editor):
    Competition = apps.get_model("dpnk", "Competition")
    CommuteMode = apps.get_model("dpnk", "CommuteMode")
    for competition in Competition.objects.all():
        competition.commute_modes.set(CommuteMode.objects.filter(slug__in=('bicycle', 'by_foot')))
        competition.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0074_auto_20170512_1943'),
    ]

    operations = [
        migrations.RunPython(set_default_commute_modes),
    ]
