# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0078_auto_20170621_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidiary',
            name='company',
            field=smart_selects.db_fields.ChainedForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsidiaries', to='dpnk.Company'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Název týmu'),
        ),
    ]
