# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0080_auto_20170826_1227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamInCampaign',
        ),
        migrations.AddField(
            model_name='userattendance',
            name='personal_data_opt_in',
            field=models.BooleanField(default=False, verbose_name='Souhlas se zpracováním osobních údajů.'),
        ),
    ]
