# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0082_personal_opt_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='personal_data_opt_in',
        ),
    ]
