# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 10:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations
import stdnumfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0084_auto_20170905_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address_district',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='company_address_district',
        ),
        migrations.RemoveField(
            model_name='subsidiary',
            name='address_district',
        ),
        migrations.AlterField(
            model_name='company',
            name='dic',
            field=stdnumfield.models.StdNumField(alphabets=[None], blank=True, default='', formats=['cz.dic'], null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{2}[0-9]*$', 'DIČ musí být číslo uvozené dvoupísmeným identifikátorem státu.')], verbose_name='DIČ'),
        ),
    ]
