# Generated by Django 2.0.2 on 2018-03-23 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0092_trigram_extension'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='subsidiary',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.PositiveIntegerField(blank=True, choices=[(20001, 'Nový'), (20002, 'Přijat k sestavení'), (20003, 'Sestaven'), (20004, 'Odeslán'), (20005, 'Doručení potvrzeno'), (20006, 'Dosud nedoručeno'), (20007, 'Reklamován'), (1, 'Nová'), (2, 'Zrušena'), (7, 'Odmítnuta'), (4, 'Zahájena'), (5, 'Očekává potvrzení'), (7, 'Platba zamítnuta, prostředky nemožno vrátit, řeší PayU'), (99, 'Platba přijata'), (888, 'Nesprávný status -- kontaktovat PayU'), (1005, 'Platba akceptována organizací'), (1008, 'Partner má startovné zdarma'), (1006, 'Faktura vystavena'), (1007, 'Faktura zaplacena'), (40001, 'Oprava v cykloservisu'), (30002, 'Potvrzen vstup do soutěže')], default=0, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_user_attendance',
            field=models.ForeignKey(default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='dpnk.UserAttendance'),
        ),
    ]
