# Generated by Django 2.0.4 on 2018-05-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0101_userattendance_last_sync_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ('-campaign', 'priority', 'name'), 'verbose_name': 'Soutěžní kategorie', 'verbose_name_plural': 'Soutěžní kategorie'},
        ),
        migrations.AddField(
            model_name='competition',
            name='priority',
            field=models.IntegerField(default=0, help_text='Vyšší priorita -> řadí se dřív', verbose_name='Prorita v řazení'),
        ),
    ]
