# Generated by Django 2.0.3 on 2018-08-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0111_campaign_club_membership_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='email_footer_cs',
            field=models.TextField(blank=True, default='', max_length=5000, null=True, verbose_name='Patička uživatelských e-mailů'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='email_footer_dsnkcs',
            field=models.TextField(blank=True, default='', max_length=5000, null=True, verbose_name='Patička uživatelských e-mailů'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='email_footer_en',
            field=models.TextField(blank=True, default='', max_length=5000, null=True, verbose_name='Patička uživatelských e-mailů'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='extra_agreement_text',
            field=models.TextField(default='', null=True, verbose_name='Další text pro uživatelské souhlas'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='extra_agreement_text_cs',
            field=models.TextField(default='', null=True, verbose_name='Další text pro uživatelské souhlas'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='extra_agreement_text_dsnkcs',
            field=models.TextField(default='', null=True, verbose_name='Další text pro uživatelské souhlas'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='extra_agreement_text_en',
            field=models.TextField(default='', null=True, verbose_name='Další text pro uživatelské souhlas'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='free_entry_cases_html_cs',
            field=models.TextField(blank=True, null=True, verbose_name='Případy, kdy je startovné zdarma'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='free_entry_cases_html_dsnkcs',
            field=models.TextField(blank=True, null=True, verbose_name='Případy, kdy je startovné zdarma'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='free_entry_cases_html_en',
            field=models.TextField(blank=True, null=True, verbose_name='Případy, kdy je startovné zdarma'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='name_cs',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='Jméno kampaně'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='name_dsnkcs',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='Jméno kampaně'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='name_en',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='Jméno kampaně'),
        ),
    ]
