# Generated by Django 2.0.6 on 2018-08-24 14:21

from django.db import migrations

def set_mailing_list_enabled(apps, schema_editor):
    Campaign = apps.get_model("dpnk", "Campaign")
    Campaign.objects.filter(mailing_list_enabled=False).update(mailing_list_enabled=None)

class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0117_auto_20180824_1414'),
    ]

    operations = [
        migrations.RunPython(set_mailing_list_enabled),
    ]
