# Generated by Django 2.0.6 on 2018-08-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0118_auto_20180824_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='mailing_list_enabled',
            field=models.NullBooleanField(default=False, unique=True, verbose_name='Povolit mailing list'),
        ),
    ]
