# Generated by Django 2.0.8 on 2018-11-22 16:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import stdnumfield.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dpnk', '0120_auto_20181120_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_create', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AddField(
            model_name='team',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_create', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='team',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_city',
            field=models.CharField(default='', max_length=50, verbose_name='Město'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_psc',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(10000)], verbose_name='PSČ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_recipient',
            field=models.CharField(blank=True, default='', help_text='Nezadávejte adresu jako název pobočky.', max_length=50, null=True, verbose_name='Adresát na faktuře'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_street',
            field=models.CharField(default='', max_length=50, verbose_name='Ulice'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_street_number',
            field=models.CharField(default='', max_length=10, verbose_name='Číslo domu'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ico',
            field=stdnumfield.models.StdNumField(alphabets=[None], blank=True, default=None, error_messages={'stdnum_format': 'IČO není zadáno ve správném formátu. Zkontrolujte že číslo má osm číslic a případně ho doplňte nulami zleva.'}, formats=['cz.dic'], help_text='Prosím zadejte IČO splečnosti.', null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'IČO musí být číslo')], verbose_name='IČO'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Například Výrobna a.s., Příspěvková p.o., Nevládka z.s., Univerzita Karlova', max_length=60, unique=True, verbose_name='Název společnosti'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company_address_city',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Město'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company_address_psc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PSČ'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company_address_recipient',
            field=models.CharField(blank=True, default='', help_text='Nezadávejte adresu jako název pobočky.', max_length=50, null=True, verbose_name='Adresát na faktuře'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company_address_street',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Ulice'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company_address_street_number',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Číslo domu'),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='address_city',
            field=models.CharField(default='', max_length=50, verbose_name='Město'),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='address_psc',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(10000)], verbose_name='PSČ'),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='address_recipient',
            field=models.CharField(blank=True, default='', help_text='Nezadávejte adresu jako název pobočky.', max_length=50, null=True, verbose_name='Název pobočky'),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='address_street',
            field=models.CharField(default='', max_length=50, verbose_name='Ulice'),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='address_street_number',
            field=models.CharField(default='', max_length=10, verbose_name='Číslo domu'),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='city',
            field=models.ForeignKey(help_text='Váš tým se zařadí do žebříčků za nejbližší soutěžní město.', on_delete=django.db.models.deletion.CASCADE, to='dpnk.City', verbose_name='Soutěžní město'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, help_text='Nechcete soutěžit pod svým skutečným jménem? Napište přezdívku, podle které Vás kolegové poznají.', max_length=60, null=True, verbose_name='Přezdívka'),
        ),
    ]
