# Generated by Django 2.0.9 on 2018-12-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0121_add_with_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telephone_opt_in',
            field=models.NullBooleanField(default=None, verbose_name='Povolení telefonovat'),
        ),
    ]
