# Generated by Django 2.0.9 on 2019-04-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0128_auto_20190326_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='commutemode',
            name='button_html',
            field=models.TextField(default='', verbose_name='Html of selector buttons'),
        ),
        migrations.AlterField(
            model_name='campaigntype',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Identifikátor typu kampaně'),
        ),
    ]
