# Generated by Django 2.0.13 on 2019-07-19 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smmapdfs', '0002_auto_20180611_1830'),
        ('dpnk', '0136_cityincampaigndiploma_cityincampaigndiplomafield'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='city_in_campaign_diploma_sandwich_type',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_in_campaign_diploma_campaign', to='smmapdfs.PdfSandwichType'),
        ),
    ]
