# Generated by Django 2.0.13 on 2019-08-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0138_auto_20190819_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigntype',
            name='contact_email',
            field=models.CharField(default='kontakt@dopracenakole.cz', max_length=80, verbose_name='Kontaktní e-mail'),
        ),
        migrations.AddField(
            model_name='campaigntype',
            name='language_prefixes',
            field=models.CharField(choices=[('dpnk', 'Do práce na kole'), ('dsnk', 'Do školy na kole')], default='dpnk', max_length=16, verbose_name='Jazyková sada'),
        ),
        migrations.AddField(
            model_name='campaigntype',
            name='sitetree_postfix',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Postfix pro menu'),
        ),
        migrations.AddField(
            model_name='campaigntype',
            name='web',
            field=models.URLField(blank=True, default='http://www.dopracenakole.cz', verbose_name='Web kampáně'),
        ),
        migrations.AddField(
            model_name='campaigntype',
            name='wp_api_url',
            field=models.URLField(blank=True, default='http://www.dopracenakole.cz', null=True, verbose_name='Adresa pro Wordpress API se články'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='contact_email',
            field=models.CharField(blank=True, default='kontakt@dopracenakole.cz', max_length=80, null=True, verbose_name='Deprecated: Kontaktní e-mail'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='language_prefixes',
            field=models.CharField(choices=[('dpnk', 'Do práce na kole'), ('dsnk', 'Do školy na kole')], default='dpnk', max_length=16, verbose_name='Deprecated: Jazyková sada'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=60, null=True, verbose_name='Deprecated: Jméno kampaně'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name_cs',
            field=models.CharField(max_length=60, null=True, verbose_name='Deprecated: Jméno kampaně'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name_dsnkcs',
            field=models.CharField(max_length=60, null=True, verbose_name='Deprecated: Jméno kampaně'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name_en',
            field=models.CharField(max_length=60, null=True, verbose_name='Deprecated: Jméno kampaně'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='sitetree_postfix',
            field=models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='Deprecated: Postfix pro menu'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='web',
            field=models.URLField(blank=True, default='http://www.dopracenakole.cz', null=True, verbose_name='Deprecated: Web kampáně'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='wp_api_url',
            field=models.URLField(blank=True, default='http://www.dopracenakole.cz', null=True, verbose_name='Deprecated: Adresa pro Wordpress API se články'),
        ),
    ]
