# Generated by Django 2.2.7 on 2019-11-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0140_auto_20191125_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityincampaigndiplomafield',
            name='field',
            field=models.CharField(max_length=36, verbose_name='field'),
        ),
        migrations.AlterField(
            model_name='diplomafield',
            name='field',
            field=models.CharField(max_length=36, verbose_name='field'),
        ),
        migrations.AlterField(
            model_name='teamdiplomafield',
            name='field',
            field=models.CharField(max_length=36, verbose_name='field'),
        ),
    ]
