# Generated by Django 2.2.11 on 2020-03-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0144_auto_20200303_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='commutemode',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Body'),
        ),
    ]
