# Generated by Django 2.2.11 on 2020-03-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0145_commutemode_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattendance',
            name='trip_points_total',
            field=models.FloatField(editable=False, null=True),
        ),
    ]
