# Generated by Django 2.2.11 on 2020-03-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0146_userattendance_trip_points_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='show_charitative_choices',
            field=models.BooleanField(default=False, verbose_name='Ukázat volbu charitativní organizace ve výsledích'),
        ),
        migrations.AlterField(
            model_name='userattendance',
            name='trip_points_total',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
