# Generated by Django 2.2.11 on 2020-03-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0146_userattendance_trip_points_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattendance',
            name='trip_points_total',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
