# Generated by Django 2.2.11 on 2020-03-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0148_dpnknotificationtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dpnknotificationtemplate',
            name='url_cs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dpnknotificationtemplate',
            name='url_dsnkcs',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dpnknotificationtemplate',
            name='url_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
