# Generated by Django 2.2.11 on 2020-03-27 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0147_auto_20200327_2020'),
        ('dpnk', '0149_auto_20200327_0038'),
    ]

    operations = [
    ]
