# Generated by Django 2.2.12 on 2020-05-28 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0151_auto_20200402_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='results_text',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Text u výsledek'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='previous_campaign',
            field=models.ForeignKey(blank=True, help_text='Kampaň, ze které se přebírá velikost trička, nazev týmu atd... při vytváření nové účasti v kampani', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dpnk.Campaign', verbose_name='Předchozí kampaň'),
        ),
        migrations.AlterField(
            model_name='commutemode',
            name='duration_important',
            field=models.BooleanField(default=True, verbose_name='Je doba důležité'),
        ),
    ]
