# Generated by Django 2.2.13 on 2020-08-27 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0152_auto_20200528_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Rekola', max_length=255, verbose_name='Jméno')),
                ('eshop_url', models.CharField(default='https://obchod.auto-mat.cz', max_length=255, verbose_name='E-Shop URL')),
                ('teaser_img', models.ImageField(blank=True, null=True, upload_to='3rd_party_voucher_teaser_images/image', verbose_name='Teaser image')),
            ],
            options={
                'verbose_name': 'Druh voucheru třetí strany',
                'verbose_name_plural': 'Druhy voucherů třetích stran',
            },
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('rekola', 'ReKola'), ('sportlife', 'SportLife'), ('am-eshop', 'Automat benefiční obchod')], default='rekola', max_length=10, verbose_name='DEPRECATED'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='voucher_type1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dpnk.VoucherType', verbose_name='Typ voucheru'),
        ),
    ]
