# Generated by Django 2.2.13 on 2020-08-27 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0153_auto_20200827_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='amount',
            field=models.TextField(blank=True, null=True, verbose_name='hodnota'),
        ),
    ]
