# Generated by Django 2.2.13 on 2020-08-31 22:24

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smmapdfs', '0003_auto_20191126_1611'),
        ('dpnk', '0154_voucher_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='good_till',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vouchertype',
            name='sandwich_type',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='smmapdfs.PdfSandwichType'),
        ),
        migrations.CreateModel(
            name='VoucherPDFField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=36, verbose_name='field')),
                ('font_size', models.IntegerField(default=16, verbose_name='Font size')),
                ('x', models.FloatField(default=0, verbose_name='X (mm)')),
                ('y', models.FloatField(default=0, verbose_name='Y (mm)')),
                ('alignment', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], default='left', max_length=36, verbose_name='alignment')),
                ('stroke_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('fill_color', colorfield.fields.ColorField(default='#000000', max_length=18)),
                ('font', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smmapdfs.PdfSandwichFont')),
                ('pdfsandwich_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='smmapdfs.PdfSandwichType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VoucherPDF',
            fields=[
                ('pdfsandwichabc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='smmapdfs.PdfSandwichABC')),
                ('obj', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dpnk.Voucher')),
            ],
            bases=('smmapdfs.pdfsandwichabc',),
        ),
    ]
