# Generated by Django 2.2.13 on 2020-11-17 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0155_auto_20200831_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='commutemode',
            name='description',
            field=models.TextField(blank=True, default=None, help_text='A basic description of the commute mode.', null=True, verbose_name='Vysvětlivka výběru módu'),
        ),
        migrations.AddField(
            model_name='commutemode',
            name='description_cs',
            field=models.TextField(blank=True, default=None, help_text='A basic description of the commute mode.', null=True, verbose_name='Vysvětlivka výběru módu'),
        ),
        migrations.AddField(
            model_name='commutemode',
            name='description_dsnkcs',
            field=models.TextField(blank=True, default=None, help_text='A basic description of the commute mode.', null=True, verbose_name='Vysvětlivka výběru módu'),
        ),
        migrations.AddField(
            model_name='commutemode',
            name='description_en',
            field=models.TextField(blank=True, default=None, help_text='A basic description of the commute mode.', null=True, verbose_name='Vysvětlivka výběru módu'),
        ),
        migrations.AddField(
            model_name='commutemode',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='commute_mode_icons/'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='dpnk.CampaignType', verbose_name='Typ kampaně'),
        ),
    ]
