# Generated by Django 2.2.17 on 2020-12-22 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0011_auto_20190223_2138'),
        ('dpnk', '0156_auto_20201117_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Gallery', verbose_name='Galerie fotek'),
        ),
        migrations.AddField(
            model_name='company',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photologue.Photo', verbose_name='Ikona'),
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Gallery', verbose_name='Galerie fotek'),
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photologue.Photo', verbose_name='Ikona'),
        ),
        migrations.AddField(
            model_name='team',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photologue.Photo', verbose_name='Ikona'),
        ),
        migrations.AddField(
            model_name='trip',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Gallery', verbose_name='Galerie fotek'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Gallery', verbose_name='Galerie fotek'),
        ),
        migrations.AlterField(
            model_name='commutemode',
            name='description',
            field=models.TextField(blank=True, default=None, help_text='A basic description of the commute mode.', null=True, verbose_name='Vysvětlivka módu'),
        ),
        migrations.AlterField(
            model_name='commutemode',
            name='description_cs',
            field=models.TextField(blank=True, default=None, help_text='A basic description of the commute mode.', null=True, verbose_name='Vysvětlivka módu'),
        ),
        migrations.AlterField(
            model_name='commutemode',
            name='description_dsnkcs',
            field=models.TextField(blank=True, default=None, help_text='A basic description of the commute mode.', null=True, verbose_name='Vysvětlivka módu'),
        ),
        migrations.AlterField(
            model_name='commutemode',
            name='description_en',
            field=models.TextField(blank=True, default=None, help_text='A basic description of the commute mode.', null=True, verbose_name='Vysvětlivka módu'),
        ),
    ]
