# Generated by Django 2.2.13 on 2021-01-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0158_auto_20210105_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityincampaign',
            name='organizer',
            field=models.TextField(default='', verbose_name='Jméno pořadatele'),
        ),
        migrations.AddField(
            model_name='cityincampaign',
            name='organizer_url',
            field=models.URLField(default='', verbose_name='URL pořadatele'),
        ),
    ]
