# Generated by Django 2.2.13 on 2021-01-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0159_auto_20210113_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Popis cesty'),
        ),
        migrations.AlterField(
            model_name='cityincampaign',
            name='organizer',
            field=models.TextField(blank=True, default='', verbose_name='Jméno pořadatele'),
        ),
        migrations.AlterField(
            model_name='cityincampaign',
            name='organizer_url',
            field=models.URLField(blank=True, default='', verbose_name='URL pořadatele'),
        ),
    ]
