# Generated by Django 2.2.20 on 2021-05-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0163_userattendance_working_rides_base_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattendance',
            name='working_rides_base_count',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
