# Generated by Django 2.2.21 on 2021-05-16 19:09

from django.db import migrations, models
import dpnk.models.invoice


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0164_auto_20210504_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigntype',
            name='frontend_url',
            field=models.URLField(default='https://dpnk-frontend.s3-eu-west-1.amazonaws.com/2021.10/', verbose_name='Adresa pro statické frontendové soubory'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_pdf',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=dpnk.models.invoice.get_invoice_dir, verbose_name='PDF faktury'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_xml',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to=dpnk.models.invoice.get_invoice_dir, verbose_name='XML faktury'),
        ),
    ]
