# Generated by Django 2.2.21 on 2021-06-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0165_auto_20210516_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityincampaign',
            name='data_export',
            field=models.FileField(blank=True, max_length=255, upload_to=''),
        ),
        migrations.AddField(
            model_name='cityincampaign',
            name='data_export_password',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
