# Generated by Django 2.2.24 on 2021-08-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0166_auto_20210627_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityincampaign',
            name='data_export',
            field=models.FileField(blank=True, max_length=255, upload_to='city_data_exports'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['date', '-direction', '-id', 'source_application'], name='dpnk_trip_date_2c90e4_idx'),
        ),
    ]
