# Generated by Django 2.2.24 on 2022-03-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0168_auto_20220314_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='fakturoid_invoice_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL Fakturoid web faktúry'),
        ),
    ]
