# Generated by Django 2.2.28 on 2024-02-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0171_auto_20240201_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Poznámka'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.PositiveIntegerField(blank=True, choices=[(20001, 'Nový'), (20002, 'Přijat k sestavení'), (20003, 'Sestaven'), (20004, 'Odeslán'), (20005, 'Doručení potvrzeno'), (20006, 'Dosud nedoručeno'), (20007, 'Reklamován (zaviněná)'), (20008, 'Reklamován (nezaviněná)'), (1, 'Nová'), (2, 'Zrušena'), (7, 'Odmítnuta'), (4, 'Zahájena'), (5, 'Očekává potvrzení'), (7, 'Platba zamítnuta, prostředky nemožno vrátit, řeší PayU'), (99, 'Platba přijata'), (888, 'Nesprávný status -- kontaktovat PayU'), (1005, 'Platba akceptována organizací'), (1008, 'Partner má startovné zdarma'), (1006, 'Faktura vystavena'), (1007, 'Faktura zaplacena'), (40001, 'Oprava v cykloservisu'), (30002, 'Potvrzen vstup do soutěže')], default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.PositiveIntegerField(choices=[(20001, 'Nový'), (20002, 'Přijat k sestavení'), (20003, 'Sestaven'), (20004, 'Odeslán'), (20005, 'Doručení potvrzeno'), (20006, 'Dosud nedoručeno'), (20007, 'Reklamován (zaviněná)'), (20008, 'Reklamován (nezaviněná)'), (1, 'Nová'), (2, 'Zrušena'), (7, 'Odmítnuta'), (4, 'Zahájena'), (5, 'Očekává potvrzení'), (7, 'Platba zamítnuta, prostředky nemožno vrátit, řeší PayU'), (99, 'Platba přijata'), (888, 'Nesprávný status -- kontaktovat PayU'), (1005, 'Platba akceptována organizací'), (1008, 'Partner má startovné zdarma'), (1006, 'Faktura vystavena'), (1007, 'Faktura zaplacena'), (40001, 'Oprava v cykloservisu'), (30002, 'Potvrzen vstup do soutěže')], default=0, verbose_name='Status'),
        ),
    ]
