# Generated by Django 2.2.28 on 2024-02-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0172_auto_20240214_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order_number',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Číslo objednávky (nepovinné)'),
        ),
    ]
