# Generated by Django 2.2.28 on 2024-03-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0173_auto_20240219_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattendance',
            name='discount_coupon_used',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datum použití slevového kupónu'),
        ),
    ]
