# Generated by Django 2.2.28 on 2024-06-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0174_userattendance_discount_coupon_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='minimum_percentage',
            field=models.FloatField(default=66.6, verbose_name='Minimální procento pro kvalifikaci do pravidelnostní soutěže'),
        ),
    ]
