# Generated by Django 2.2.28 on 2024-11-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0178_auto_20241113_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('company', 'Organizace'), ('family', 'Rodina'), ('school', 'Škola')], default='company', max_length=20, verbose_name='Typ organizace'),
        ),
    ]
