# Generated by Django 2.2.28 on 2024-12-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0180_auto_20241126_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pay_subject',
            field=models.CharField(blank=True, choices=[('individual', 'Jednotlivec'), ('voucher', 'Slevový kupón'), ('company', 'Organizace'), ('school', 'Škola')], max_length=20, null=True, verbose_name='Platobní subjekt'),
        ),
    ]
