# Generated by Django 2.2.28 on 2025-01-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0182_auto_20250103_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay_category',
            field=models.CharField(blank=True, choices=[('entry_fee', 'Startovné'), ('donation', 'Dar'), ('entry_fee-donation', 'Startovné a dar')], max_length=20, null=True, verbose_name='Platobní kategorie'),
        ),
    ]
