# Generated by Django 2.2.28 on 2025-01-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0184_auto_20250103_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('cs', 'Čeština'), ('en', 'Angličtna'), ('sk', 'Slovenština')], default='cs', help_text='V tomto jazyce Vám budou přicházet e-maily z registračního systému', max_length=16, verbose_name='Jazyk e-mailové komunikace'),
        ),
    ]
