# Generated by Django 2.2.28 on 2025-03-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0185_auto_20250127_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyadmin',
            name='package_requested',
            field=models.BooleanField(default=False, help_text='Firemní koordinátor žádá o tričkové balíčky pro zaměstnance', verbose_name='Žádost o balíček'),
        ),
    ]
