# Generated by Django 2.2.28 on 2025-03-04 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0186_add_package_requested_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyadmin',
            name='package_requested',
        ),
    ]
