# Generated by Django 2.2.28 on 2025-11-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0187_add_box_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Popis'),
        ),
    ]
