# Generated by Django 2.2.28 on 2025-08-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0187_add_box_request'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subsidiary',
            index=models.Index(fields=['company'], name='subsidiary_company_idx'),
        ),
    ]
