# Generated by Django 2.2.28 on 2025-12-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0188_competition_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, help_text='&lt;h1&gt;Chystáme pro vás Lednovou výzvu Do práce na kole, pěšky či poklusem &lt;YEAR&gt;.&lt;/h1&gt;&lt;p&gt;Výzva jednotlivců se uskuteční v termínu &lt;COMPETITION_PHASE_INTERVAL_DATE&gt;.&lt;/p&gt;&lt;p&gt;Účast je zdarma, registraci otevíráme &lt;REGISTRATION_PHASE_START_DATE&gt; zde.&lt;/p&gt;', max_length=5000, null=True, verbose_name='Popis'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='description_cs',
            field=models.TextField(blank=True, help_text='&lt;h1&gt;Chystáme pro vás Lednovou výzvu Do práce na kole, pěšky či poklusem &lt;YEAR&gt;.&lt;/h1&gt;&lt;p&gt;Výzva jednotlivců se uskuteční v termínu &lt;COMPETITION_PHASE_INTERVAL_DATE&gt;.&lt;/p&gt;&lt;p&gt;Účast je zdarma, registraci otevíráme &lt;REGISTRATION_PHASE_START_DATE&gt; zde.&lt;/p&gt;', max_length=5000, null=True, verbose_name='Popis'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='description_dsnkcs',
            field=models.TextField(blank=True, help_text='&lt;h1&gt;Chystáme pro vás Lednovou výzvu Do práce na kole, pěšky či poklusem &lt;YEAR&gt;.&lt;/h1&gt;&lt;p&gt;Výzva jednotlivců se uskuteční v termínu &lt;COMPETITION_PHASE_INTERVAL_DATE&gt;.&lt;/p&gt;&lt;p&gt;Účast je zdarma, registraci otevíráme &lt;REGISTRATION_PHASE_START_DATE&gt; zde.&lt;/p&gt;', max_length=5000, null=True, verbose_name='Popis'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='description_en',
            field=models.TextField(blank=True, help_text='&lt;h1&gt;Chystáme pro vás Lednovou výzvu Do práce na kole, pěšky či poklusem &lt;YEAR&gt;.&lt;/h1&gt;&lt;p&gt;Výzva jednotlivců se uskuteční v termínu &lt;COMPETITION_PHASE_INTERVAL_DATE&gt;.&lt;/p&gt;&lt;p&gt;Účast je zdarma, registraci otevíráme &lt;REGISTRATION_PHASE_START_DATE&gt; zde.&lt;/p&gt;', max_length=5000, null=True, verbose_name='Popis'),
        ),
    ]
