# Generated by Django 2.2.28 on 2026-01-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0190_auto_20260121_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='competitor_type',
            field=models.CharField(choices=[('single_user', 'Jednotliví soutěžící'), ('liberos', 'Liberos'), ('team', 'Týmy'), ('company', 'Soutěž organizací'), ('subsidiary', 'Soutěž poboček')], help_text='Určuje, zdali bude soutěž týmová, nebo pro jednotlivce. Ostatní volby vybírejte jen pokud víte, k čemu slouží.', max_length=16, verbose_name='Počet soutěžících'),
        ),
    ]
