# Generated by Django 2.2.28 on 2026-05-12 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0191_auto_20260122_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionresult',
            name='subsidiary',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsidiary_results', to='dpnk.Company'),
        ),
    ]
