# Generated by Django 2.2.28 on 2026-05-15 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0192_competitionresult_subsidiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionresult',
            name='subsidiary',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsidiary_results', to='dpnk.Subsidiary'),
        ),
    ]
