# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161107131156 on 2016-12-19 15:12
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0001_initial'),
        ('dpnk', '0043_auto_20161219_1512'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='DiscountCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True, verbose_name='token')),
                ('discount', models.PositiveIntegerField(default=100, verbose_name='sleva (v procentech)')),
                ('note', models.CharField(blank=True, max_length=50, null=True, verbose_name='poznámka')),
                ('receiver', models.CharField(blank=True, max_length=50, null=True, verbose_name='příjemce')),
                ('sent', models.BooleanField(default=False, verbose_name='Odeslaný')),
            ],
            options={
                'verbose_name_plural': 'Slevové kupóny',
                'verbose_name': 'Slevový kupón',
                'db_table': 'coupons_discountcoupon',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='DiscountCouponType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='jméno typu voucheru')),
                ('prefix', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_prefix', message='Prefix musí sestávat pouze z velkých písmen', regex='^[A-Z]*$')], verbose_name='prefix')),
            ],
            options={
                'verbose_name_plural': 'Typy slevového kupónu',
                'verbose_name': 'Typ slevového kupónu',
                'db_table': 'coupons_discountcoupontype',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='discountcoupon',
            name='coupon_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='coupons.DiscountCouponType', verbose_name='typ voucheru'),
        ),
        migrations.AddField(
            model_name='discountcoupon',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discountcoupon_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterUniqueTogether(
            name='discountcoupon',
            unique_together=set([('token', 'coupon_type')]),
        ),
        migrations.AlterModelTable(
            name='discountcoupon',
            table=None,
        ),
        migrations.AlterModelTable(
            name='discountcoupontype',
            table=None,
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
