# Generated by Django 2.2.7 on 2019-11-29 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smmapdfs', '0003_auto_20191126_1611'),
        ('coupons', '0003_auto_20191125_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcoupontype',
            name='sandwich_type',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='smmapdfs.PdfSandwichType'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='coupon_pdf',
            field=models.FileField(blank=True, null=True, upload_to='coupons', verbose_name='DEPRECATED'),
        ),
        migrations.AlterField(
            model_name='discountcoupon',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='DEPRECATED'),
        ),
        migrations.CreateModel(
            name='CouponSandwich',
            fields=[
                ('pdfsandwichabc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='smmapdfs.PdfSandwichABC')),
                ('obj', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='coupons.DiscountCoupon')),
            ],
            bases=('smmapdfs.pdfsandwichabc',),
        ),
        migrations.CreateModel(
            name='CouponField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=36, verbose_name='field')),
                ('font_size', models.IntegerField(default=16, verbose_name='Font size')),
                ('x', models.FloatField(default=0, verbose_name='X (mm)')),
                ('y', models.FloatField(default=0, verbose_name='Y (mm)')),
                ('alignment', models.CharField(choices=[('left', 'Left'), ('right', 'Right'), ('center', 'Center')], default='left', max_length=36, verbose_name='alignment')),
                ('font', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smmapdfs.PdfSandwichFont')),
                ('pdfsandwich_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='smmapdfs.PdfSandwichType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
