# Generated by Django 2.2.9 on 2020-02-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_auto_20191204_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcoupon',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='jméno příjemce'),
        ),
    ]
