version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch

    steps:
      - checkout
      - run: echo "$(date +%Y).${CIRCLE_BUILD_NUM}" > apps/dpnk/static/version.txt
      - run: echo "$(git rev-parse HEAD)" > apps/dpnk/static/git-commit.txt
      - run: |
            LAST_SUCCESSFUL_BUILD_URL="https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/tree/$CIRCLE_BRANCH?filter=completed&limit=1"
            LAST_SUCCESSFUL_COMMIT=`curl -Ss -u "$CIRCLE_TOKEN:" $LAST_SUCCESSFUL_BUILD_URL | jq -r '.[0]["vcs_revision"]'`
            #first commit in a branch
            if [[ ${LAST_SUCCESSFUL_COMMIT} == "null" ]]; then
              COMMITS="origin/master"
            else
              COMMITS="${CIRCLE_SHA1}..${LAST_SUCCESSFUL_COMMIT}"
            fi
            export COMMITS
      - setup_remote_docker:
          reusable: true
      - run:
         name: Build base docker image
         command: |
           if scripts/test_changes monorepo/docker-base-image ; then
             cd /home/circleci/project/monorepo/docker-base-image
             docker build -t dopracenakole-base .
             cd /home/circleci/project
           fi
      - run:
         name: Deploy base docker image
         command: |
           if scripts/test_changes monorepo/docker-base-image ; then
            if [ "$DOCKER_USER" != "" ] ; then
              TAG="$(date +%Y).${CIRCLE_BUILD_NUM}"
              docker tag dopracenakole-base:latest auto0mat/dopracenakole-base:$TAG
              docker tag dopracenakole-base:latest auto0mat/dopracenakole-base:latest
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push auto0mat/dopracenakole-base:$TAG
              docker push auto0mat/dopracenakole-base:latest
            fi
           fi
      - run:
         name: Build Docker image
         command: |
           if scripts/test_changes --invert-match monorepo/ ; then
             cd /home/circleci/project
             docker build -t dopracenakole .
           fi
      - run:
         name: Deploy test Docker image
         command: |
           if scripts/test_changes --invert-match monorepo/ ; then
            if [ "$DOCKER_USER" != "" ] ; then
              TAG="$(date +%Y).${CIRCLE_BUILD_NUM}"
              docker tag dopracenakole:latest auto0mat/dopracenakole:$TAG
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push auto0mat/dopracenakole:$TAG
            fi
           fi
      - run:
         name: Build test Docker image
         command: |
           if scripts/test_changes --invert-match monorepo/ ; then
             docker build -t dopracenakole-test -f TestDockerfile .
           fi
      - run:
         name: Start PostGIS container
         command: |
           if scripts/test_changes --invert-match monorepo/ ; then
            docker run -d --hostname dpnk-postgres --name dpnk-postgres -e POSTGRES_PASSWORD=password mdillon/postgis:9.6
           fi
      - run:
         name: Start RabbitMQ container
         command: |
           if scripts/test_changes --invert-match monorepo/ ; then
            docker run -d --hostname dpnk-rabbit --name dpnk-rabbit rabbitmq
           fi
      - run:
         name: Test Docker container in Django
         command: |
           if scripts/test_changes --invert-match monorepo/ ; then
            sleep 10
            docker run \
               --entrypoint="/home/aplikace/docker-test-entrypoint.sh" \
               --env DPNK_DB_HOST=postgres \
               --env DPNK_SECRET_KEY=secret \
               --env DPNK_DB_NAME=postgres \
               --env DPNK_DB_USER=postgres \
               --env DPNK_DB_PASSWORD=password \
               --env DPNK_BROKER_URL="amqp://rabbit" \
               --env FAKTUROID_INVOICE_NUMBER_WIDTH=4 \
               --env FAKTUROID_BASE_REST_API_URL="https://app.fakturoid.cz/api/v2" \
               --env FAKTUROID_TEST_USER_ACCOUNT=$FAKTUROID_TEST_USER_ACCOUNT \
               --env FAKTUROID_TEST_USER_EMAIL="$FAKTUROID_TEST_USER_EMAIL" \
               --env FAKTUROID_TEST_API_KEY=$FAKTUROID_TEST_API_KEY \
               --env FAKTUROID_TEST_USER_AGENT_HEADER="$FAKTUROID_TEST_USER_AGENT_HEADER" \
               --link dpnk-rabbit:rabbit \
               --link dpnk-postgres:postgres \
               --name dpnk-test \
               dopracenakole-test
           fi
      - store_artifacts:
          path: /tmp/reports
          destination: reports
