version: 2
jobs:
  build:
    working_directory: /home/aplikace
    docker:
      - image: python:3.5

    steps:
      - checkout
      - run: echo "$(date +%Y).${CIRCLE_BUILD_NUM} $(git rev-parse --short HEAD)" > apps/dpnk/static/version.txt
      - setup_remote_docker:
          reusable: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.03.1-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
         name: Build Docker image
         command: docker build -t dopracenakole .
      - run:
         name: Deploy test Docker image
         command: |
            if [ "$DOCKER_USER" != "" ] ; then
              TAG="$(date +%Y).${CIRCLE_BUILD_NUM}"
              docker tag dopracenakole:latest auto0mat/dopracenakole-test:$TAG
              if [ "$CIRCLE_BRANCH" == "devel" ] ; then
                 docker tag dopracenakole:latest auto0mat/dopracenakole-test:latest
              fi
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker push auto0mat/dopracenakole-test:$TAG
              if [ "$CIRCLE_BRANCH" == "devel" ] ; then
                 docker push auto0mat/dopracenakole-test:latest
              fi
            fi
      - run:
         name: Build Docker image
         command: docker build -t dopracenakole-test -f TestDockerfile .
      - run:
         name: Start PostGIS container
         command: |
            docker run -d --hostname dpnk-postgres --name dpnk-postgres -e POSTGRES_PASSWORD=password mdillon/postgis:9.6
      - run:
         name: Start RabbitMQ container
         command: |
            docker run -d --hostname dpnk-rabbit --name dpnk-rabbit rabbitmq
      - run:
         name: Test Docker container in Django
         command: |
            sleep 10
            docker run \
               --entrypoint="/home/aplikace/docker-test-entrypoint.sh" \
               --env DPNK_DB_HOST=postgres \
               --env DPNK_SECRET_KEY=secret \
               --env DPNK_DB_NAME=postgres \
               --env DPNK_DB_USER=postgres \
               --env DPNK_DB_PASSWORD=password \
               --env DPNK_BROKER_URL="amqp://rabbit" \
               --link dpnk-rabbit:rabbit \
               --link dpnk-postgres:postgres \
               --name dpnk-test \
               dopracenakole-test

      - store_artifacts:
          path: /tmp/reports
          destination: reports
