# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160531101208 on 2017-02-15 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('t_shirt_delivery', '0003_data_link_box_team_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidiarybox',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='subsidiarybox',
            name='customer_sheets',
            field=models.FileField(blank=True, null=True, upload_to='customer_sheets', verbose_name='Zákaznické listy'),
        ),
        migrations.AddField(
            model_name='subsidiarybox',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='teampackage',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='teampackage',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='packagetransaction',
            name='delivery_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_shirt_delivery.DeliveryBatch', verbose_name='Dávka objednávek'),
        ),
        migrations.AlterField(
            model_name='packagetransaction',
            name='tracking_number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Tracking number'),
        ),
        migrations.AlterModelTable(
            name='deliverybatch',
            table=None,
        ),
        migrations.AlterModelTable(
            name='packagetransaction',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tshirtsize',
            table=None,
        ),
    ]
