# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160531101208 on 2017-02-14 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('t_shirt_delivery', '0003_data_link_box_team_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagetransaction',
            name='delivery_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_shirt_delivery.DeliveryBatch', verbose_name='Dávka objednávek'),
        ),
        migrations.AlterField(
            model_name='packagetransaction',
            name='tracking_number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Tracking number'),
        ),
        migrations.AlterModelTable(
            name='deliverybatch',
            table=None,
        ),
        migrations.AlterModelTable(
            name='packagetransaction',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tshirtsize',
            table=None,
        ),
    ]
