# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160531101208 on 2017-02-17 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_shirt_delivery', '0004_auto_20170214_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagetransaction',
            options={'verbose_name': 'Transakce trika', 'verbose_name_plural': 'Transakce trika'},
        ),
        migrations.AlterModelOptions(
            name='subsidiarybox',
            options={'verbose_name': 'Krabice pro pobočku', 'verbose_name_plural': 'Krabice pro pobočky'},
        ),
        migrations.AlterField(
            model_name='deliverybatch',
            name='tnt_order',
            field=models.FileField(blank=True, null=True, upload_to='csv_delivery', verbose_name='CSV objednávka'),
        ),
        migrations.AlterField(
            model_name='packagetransaction',
            name='tracking_number',
            field=models.PositiveIntegerField(default=None, null=True, unique=True, verbose_name='Tracking number'),
        ),
    ]
