# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-06 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_shirt_delivery', '0005_auto_20170314_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagetransaction',
            name='tracking_number',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, unique=True, verbose_name='Tracking number'),
        ),
    ]
