# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-14 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_shirt_delivery', '0007_auto_20170414_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverybatch',
            name='customer_sheets',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='customer_sheets', verbose_name='Zákaznické listy'),
        ),
        migrations.AlterField(
            model_name='deliverybatch',
            name='tnt_order',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='csv_delivery', verbose_name='CSV objednávka'),
        ),
        migrations.AlterField(
            model_name='subsidiarybox',
            name='customer_sheets',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='customer_sheets', verbose_name='Zákaznické listy'),
        ),
        migrations.AlterField(
            model_name='tshirtsize',
            name='t_shirt_preview',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='t_shirt_preview', verbose_name='Náhled trika'),
        ),
    ]
