# Generated by Django 2.0.13 on 2019-03-03 12:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0125_team_gallery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('t_shirt_delivery', '0011_auto_20180510_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBatchDeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Datum vytvoření')),
                ('deadline', models.DateTimeField()),
                ('delivery_from', models.DateTimeField(null=True)),
                ('delivery_to', models.DateTimeField(null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliverybatchdeadline_create', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpnk.Campaign', verbose_name='Kampaň')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliverybatchdeadline_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
        ),
    ]
