# Generated by Django 2.0.13 on 2019-04-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_shirt_delivery', '0012_deliverybatchdeadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverybatchdeadline',
            options={'verbose_name': 'Deadline dávky objednávek', 'verbose_name_plural': 'Deadline dáveky objednávek'},
        ),
        migrations.AddField(
            model_name='deliverybatch',
            name='order_pdf',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='pdf_delivery', verbose_name='PDF objednávky'),
        ),
    ]
