# Generated by Django 2.0.13 on 2019-04-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t_shirt_delivery', '0013_auto_20190408_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverybatch',
            name='combined_opt_pdf',
            field=models.FileField(blank=True, max_length=512, null=True, upload_to='pdf_opt_delivery', verbose_name='Kombinované PDF pro OPT'),
        ),
    ]
