# Generated by Django 2.0.6 on 2018-11-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravasync', '0002_auto_20180502_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stravaaccount',
            name='last_sync_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Poslední synchronizace'),
        ),
    ]
