# Generated by Django 2.2.7 on 2019-11-25 11:45

import coupons.models.discount_coupon_type
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_auto_20161219_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcoupontype',
            name='prefix',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_prefix', message='Prefix musí sestávat pouze z velkých písmen', regex='^[A-Z]*$'), coupons.models.discount_coupon_type.validate_prefix], verbose_name='prefix'),
        ),
    ]
