# Generated by Django 2.2.7 on 2019-12-04 17:32

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_auto_20191129_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponfield',
            name='fill_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='couponfield',
            name='stroke_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
