---

- name: Get listing of container versions
  hosts: "{{hosts}}"
  tasks:

    - name: Display the config
      sudo: yes
      command:
        /usr/bin/docker ps --format \{\{.Names\}\}
      register: containers
    - name: query container image versions
      sudo: yes
      shell: "/usr/bin/docker exec {{item}} cat static/version.txt"
      with_items: "{{ containers.stdout_lines}}"
      register: versions_output
    - debug:
        msg: "{{item}}"
      with_items: "{{versions_output.results|map(attribute='stdout')| list}}"
