# Generated by Django 2.0.13 on 2019-04-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psc',
            name='code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kód'),
        ),
        migrations.AlterField(
            model_name='psc',
            name='district_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Název okresu'),
        ),
        migrations.AlterField(
            model_name='psc',
            name='municipality_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Název obce'),
        ),
        migrations.AlterField(
            model_name='psc',
            name='municipality_part_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Název části obce'),
        ),
        migrations.AlterField(
            model_name='psc',
            name='post_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Název pošty'),
        ),
    ]
