# Generated by Django 2.0.13 on 2019-04-26 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivationMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Hláška')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Poznámka')),
                ('frequency_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Min pravidelnost')),
                ('frequency_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max pravidelnost')),
                ('day_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ode dne')),
                ('day_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='Do dne')),
                ('team_rank_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Od pořadí v týmu')),
                ('team_rank_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='Do pořadí v týmu')),
                ('team_backwards_rank_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Od pořadí v týmu od konce')),
                ('team_backwards_rank_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='Do pořadí v týmu od konce')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='Datum od')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='Datum do')),
                ('enabled', models.BooleanField(default=True, verbose_name='Povoleno')),
                ('priority', models.PositiveIntegerField(blank=True, null=True, verbose_name='Priorita')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motivationmessage_create', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='motivationmessage_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'Motivační hláška',
                'verbose_name_plural': 'Motivační hlášky',
            },
        ),
    ]
