# Generated by Django 2.0.13 on 2019-09-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0137_campaign_city_in_campaign_diploma_sandwich_type'),
        ('motivation_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motivationmessage',
            name='campaign_types',
            field=models.ManyToManyField(blank=True, null=True, to='dpnk.CampaignType'),
        ),
    ]
