from django.conf.urls import patterns, url

import views
from forms import AuthenticationFormDPNK
import dpnk.auth
import company_admin_views
from decorators import must_be_company_admin, must_be_in_phase, must_be_in_group, must_be_competitor, must_have_team
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import login_required as login_required_simple
from class_based_auth_views.views import LogoutView

urlpatterns = patterns(
    '',
    url(r'^tym/$',
        views.ChangeTeamView.as_view(),
        name="zmenit_tym"),
    url(r'^tym/(?P<token>[0-9A-Za-z]+)/(?P<initial_email>[^&]+)/$$',
        views.ConfirmTeamInvitationView.as_view(),
        ),
    url(r'^registrace/$',
        must_be_in_phase("registration", "compet_entry")(views.RegistrationView.as_view()),
        {'success_url': 'typ_platby'},
        name="registrace"),
    url(r'^registrace/(?P<initial_email>[^&]+)/$$',
        must_be_in_phase("registration", "compet_entry")(views.RegistrationView.as_view()),
        {'success_url': 'typ_platby'},
        name="registrace"),
    url(r'^header_bar/$',
        views.header_bar),
    url(r'^registrace/(?P<token>[0-9A-Za-z]+)/(?P<initial_email>[^&]+)/$$',
        must_be_in_phase("registration", "compet_entry")(views.RegistrationView.as_view()),
        {'success_url': 'typ_platby'}),
    url(r'^registrace_pristup/$',
        must_be_in_phase("registration", "compet_entry")(views.RegistrationAccessView.as_view()),
        ),
    url(r'^pozvanky/$',
        views.InviteView.as_view(),
        {'success_url': 'typ_platby'},
        name="pozvanky"),
    url(r'^zaslat_zadost_clenstvi/$',
        views.TeamApprovalRequest.as_view(),
        name="zaslat_zadost_clenstvi",
        ),
    url(r'^profil/$',
        views.ProfileView.as_view(),
        name="profil"),
    url(r'^dalsi_clenove/$',
        views.TeamMembers.as_view(),
        name="team_members",
        ),
    url(r'^dalsi_clenove_vysledky/$',
        views.other_team_members,
        {'template': 'registration/team_members_results.html'},
        ),
    url(r'^jizdy/$',
        views.RidesView.as_view(),
        name="jizdy",
        ),
    url(r'^profil_pristup/$',
        views.profile_access),
    url(r'^prihlasky/$',
        views.AdmissionsView.as_view(
            template_name='registration/admissions.html'
        ),
        ),
    url(r'^souteze/$',
        views.AdmissionsView.as_view(
            template_name="registration/competitions.html"
        ),
        name="competitions",
        ),
    url(r'^vysledky_souteze/(?P<competition_slug>[0-9A-Za-z_\-]+)/$',
        views.competition_results,
        {'template': 'registration/competition_results.html'}),
    url(r'^vysledky_souteze/(?P<competition_slug>[0-9A-Za-z_\-]+)/(?P<limit>[0-9]+)/$',
        views.competition_results,
        {'template': 'registration/competition_results.html'}),
    url(r'^questionnaire_answers/(?P<competition_slug>[0-9A-Za-z_\-]+)/$',
        views.questionnaire_answers_all,
        {'template': 'registration/questionnaire_answers_all.html'}),
    url(r'^otazka/(?P<questionaire_slug>[0-9A-Za-z_\-]+)/$',
        views.questionaire),
    url(r'^upravit_profil/$',
        login_required_simple(views.UpdateProfileView.as_view()),
        name="upravit_profil"),
    url(r'^working_schedule/$',
        login_required_simple(views.WorkingScheduleView.as_view()),
        name="working_schedule"),
    url(r'^upravit_trasu/$',
        login_required_simple(views.UpdateTrackView.as_view()),
        name="upravit_trasu"),
    url(r'^zmenit_triko/$',
        views.ChangeTShirtView.as_view(),
        {'success_url': 'typ_platby'},
        name="zmenit_triko"),
    url(r'^typ_platby/$',
        views.PaymentTypeView.as_view(),
        name="typ_platby"),
    url(r'^platba/$',
        views.PaymentView.as_view(),
        name="platba"),
    url(r'^statistika/(?P<variable>[0-9A-Za-z\-]+)/$',
        views.statistics),
    url(r'^denni-graf/$',
        views.daily_chart),
    url(r'^cykloservis/$',
        login_required(must_be_in_group('cykloservis')(views.BikeRepairView.as_view()))),
    url(r'^facebook_app/$',
        views.facebook_app),
    url(r'^package/$',
        views.PackageView.as_view(),
        name="package"),
    url(r'^competition_profile_notices/$',
        views.UserAttendanceView.as_view(
            template_name = "registration/competition_profile_notices.html"
        )),
    url(r'^package-confirmation/$',
        views.ConfirmDeliveryView.as_view(),
        ),
    url(r'^address/$',
        views.UserAttendanceView.as_view(
            template_name = "registration/address.html"
        )),


    # company admin:
    url(r'^spolecnost/zadost_admina/$',
        company_admin_views.CompanyAdminView.as_view(),
        name='company_admin_application',
        ),
    url(r'^spolecnost/soutez/(?P<competition_slug>[0-9A-Za-z_\-]+)/$',
        must_be_company_admin(login_required(company_admin_views.CompanyCompetitionView.as_view()))),
    url(r'^spolecnost/soutez/$',
        must_be_company_admin(login_required(company_admin_views.CompanyCompetitionView.as_view()))),
    url(r'^struktura_spolecnosti/$',
        company_admin_views.company_structure),
    url(r'^souteze/$',
        company_admin_views.competitions),
    url(r'^faktury/$',
        company_admin_views.invoices),
    url(r'^create_invoice/$',
        company_admin_views.CreateInvoiceView.as_view()),
    url(r'^zaplatit_za_uzivatele/$',
        company_admin_views.SelectUsersPayView.as_view(),
        name='company_admin_pay_for_users',
        ),
    url(r'^spolecnost/editovat_spolecnost/$',
        must_be_company_admin(login_required(company_admin_views.CompanyEditView.as_view()))),
    url(r'^spolecnost/registrace_admina/$',
        company_admin_views.CompanyAdminApplicationView.as_view()),
    url(r'^login/(?P<initial_email>[^&]+)/$$',
        views.DPNKLoginView.as_view(
            form_class=AuthenticationFormDPNK,
            template_name='base_generic_form.html',
            ),
        name='login',
        ),
    url(r'^login/$',
        views.DPNKLoginView.as_view(
            form_class=AuthenticationFormDPNK,
            template_name='base_generic_form.html',
            ),
        name='login',
        ),
    url(r'^logout/$',
        LogoutView.as_view(),
        name='logout',
        ),
    url(r'^platba_status$',
        views.payment_status),
    url(r'^platba_uspesna/(?P<trans_id>[0-9]+)/(?P<session_id>[0-9A-Za-z\-]+)/(?P<pay_type>[0-9A-Za-z]+)/$$',
        views.PaymentResult.as_view(),
        {'success': True}),
    url(r'^platba_neuspesna/(?P<trans_id>[0-9]*)/(?P<session_id>[0-9A-Za-z\-]+)/(?P<pay_type>[0-9A-Za-z]+)/(?P<error>[^&]+)/$$',
        views.PaymentResult.as_view(),
        {'success': False}),
    url(r'^zapomenute_heslo/$',
        'django.contrib.auth.views.password_reset',
        {'password_reset_form': dpnk.auth.PasswordResetForm},
        name='password_reset',
        ),
    url(r'^zapomenute_heslo/odeslano/$',
        'django.contrib.auth.views.password_reset_done',
        name='password_reset_done'),
    url(r'^zapomenute_heslo/zmena/(?P<uidb64>[0-9A-Za-z_]+)-(?P<token>.+)/$',
        'django.contrib.auth.views.password_reset_confirm',
        name='password_reset_confirm'),
    url(r'^zapomenute_heslo/dokonceno/$',
        'django.contrib.auth.views.password_reset_complete',
        name='password_reset_complete'),
    url(r'^zmena_hesla/$',
        'django.contrib.auth.views.password_change',
        name='password_change'),
    url(r'^zmena_hesla_hotovo/$',
        'django.contrib.auth.views.password_change_done',
        name='password_change_done'),
)
