# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160531101208 on 2017-01-06 19:43
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dpnk', '0046_auto_20170106_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=127, verbose_name='Name')),
                ('price', models.FloatField(default=100, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Price')),
                ('category', models.CharField(choices=[('basic', 'Základní'), ('company', 'Pro firmy')], default='basic', max_length=20, verbose_name='Category')),
                ('takes_effect_on', models.DateTimeField(verbose_name='Date, when this takes effect')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricelevel_create', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('pricable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpnk.Campaign', verbose_name='Pricable')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricelevel_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
