# Generated by Django 2.0.13 on 2019-08-02 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('price_level', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=127, verbose_name='Name')),
                ('description_html', models.TextField(verbose_name='HTML description')),
                ('category', models.CharField(default='', max_length=60, verbose_name='Category')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awardlevel_create', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awardlevel_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pricelevel',
            name='offer_ends',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date/time when the price level is no longer available.'),
        ),
        migrations.AlterField(
            model_name='pricelevel',
            name='pricable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpnk.Campaign', verbose_name='Priceable'),
        ),
        migrations.AddField(
            model_name='pricelevel',
            name='award_level',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='price_level.AwardLevel'),
        ),
    ]
