# Generated by Django 2.2.11 on 2020-03-26 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dpnk', '0146_userattendance_trip_points_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharitativeOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpnk.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='UserChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charitative_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='donation_chooser.CharitativeOrganization')),
                ('user_attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='charitative_choice', to='dpnk.UserAttendance')),
            ],
        ),
    ]
