# Generated by Django 2.2.11 on 2020-04-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_chooser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charitativeorganization',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
