* Managing AWS servers and deployments

In the ./scripts directory you will find various scripts for managing AWS deployments. The most important of which is ./status.py.

The most basic command you will run is

./sync-hosts.py

This will generate an up to date ansible-aws-inventory.yml file which will be used by the other commands.

For example running

./versions.sh dpnk

will tell you the versions of each container running on each instance in the 'dpnk' autoscaling group on aws. The list of autoscaling groups is printed when you run the sync-hosts command.

** Deploying to test

When you push to the [[https://github.com/auto-mat/do-prace-na-kole/commits/devel][devel branch]] a new docker image will be uploaded to [[https://cloud.docker.com/u/auto0mat/repository/list][docker hub]] to the [[https://cloud.docker.com/u/auto0mat/repository/docker/auto0mat/dopracenakole-test][dopracenakole-test repo]]. The image will be tagged with the [[https://circleci.com/gh/auto-mat/do-prace-na-kole/tree/devel][CircleCi build number]] as well as the tag 'latest'.

You can use the command restart_containers_on_server, which takes the IP address of a server to restart, to update the docker image which an instance is using. The 'latest' tag for the given instance type (test or prod) will be used.

#+BEGIN_EXAMPLE
./restart_containers_on_server 34.253.195.34
#+END_EXAMPLE

** Deploying to production

When you are satisfied with the code running on the test server you can move your image to the production repository. You do this with the './deploy-from-test-to-prod' command. You should pass 'Y.<circle-ci-build-number>' to this script.

#+BEGIN_EXAMPLE
./deploy-from-test-to-prod Y.410
#+END_EXAMPLE


When committing a change to the production servers it is necessary to use the 'deregister-prod' script before restarting each instance. You will then need to use the 'register-prod' script after the restart is complete. The deregister and register scripts will remove and re-add the instances to the load balancer. If you do not do this, then users will get an error if the load balancer routes requests to the instance while it is restarting. The deregister and register scripts take an instance ID.

#+BEGIN_EXAMPLE
./deregister-prod i-09d6c4d83bf6b5e77
./restart_containers_on_server 63.35.178.228
./register-prod i-09d6c4d83bf6b5e77
#+END_EXAMPLE
