#!/usr/bin/python3
import yaml
import sys
import subprocess
import argparse
import os
import requests

access_file = "~/.config/dpnk/access.yaml"
access_file_path = os.path.expanduser(access_file)

try:
  with open(access_file_path) as fd:
   ac = yaml.load(fd.read())
except FileNotFoundError:
  sys.exit("""
Expected to find an access file at {} in the format:

local:
  url: http://test.lvh.me:8021/
  token: <token>
test:
  url: https://test2019.dopracenakole.cz/
  token: <token>
prod:
  url: https://dpnk.dopracenakole.cz/
  token: <token>
  default-campaign-type: 2
  assets-template: https://dpnk-frontend.s3-eu-west-1.amazonaws.com/{}/


Where the main keys can be anything and the urls can be any url.

Tokens can be gotten acording to the docs here:
https://github.com/auto-mat/do-prace-na-kole/blob/devel/docs/API.md#authentification
""".format(access_file))


parser = argparse.ArgumentParser(description='Set frontend URL')
parser.add_argument('server', metavar='server', type=str,
                    help='Server as specified in {}. Current options are: {}'.format(access_file, ", ".join(ac.keys())))
parser.add_argument('--url', dest='url', default=None, type=str,
                    help='New URL of static assets')
parser.add_argument('--url-var', dest='url_var', default=None, type=str,
                    help='Variable to insert into url template when generating url of static assets. Set the template in your access file by setting the \'url-template\' and {} to place the variable.')
parser.add_argument('--campaign-type-id', dest='id', default=None, type=int,
                    help='Id of campaign type to configure')

args = parser.parse_args()

server = ac[args.server]
head = {"Authorization":"Token {}".format(server["token"])}
if args.id:
  id = args.id
else:
  try:
    id = server["default-campaign-type"]
  except KeyError:
    sys.exit("You must either specify a --campaign-type-id or set a default-campaign-type in your access file.")
url = '{url}rest/campaign_type/{id}/'.format(url=server["url"], id=id)
if args.url:
  frontend_url = args.url
else:
  try:
    frontend_url = server["frontend-url-template"].format(args.url_var)
  except KeyError:
    sys.exit("You must either specify a --url or set a frontend-url-template in your access file and specify a --url-var.")
payload = {'frontend_url' :  frontend_url}

print(url)

response = requests.patch(url, payload, headers=head)
print(response.text)
if response.status_code == 200:
  print("Frontend URL successfully updated.")
else:
  print("Hmm. something seems to have gone wrong.")
