#!/usr/bin/python3
import aws_dpnk
import subprocess

inventories, states = aws_dpnk.get_inventories()

for instance in states['running']:
    if instance[0] == "dpnk":
        subprocess.call(["./deregister-prod", instance[3]])
        subprocess.call(["./restart_containers_on_server", instance[2]])
        subprocess.call(["./register-prod", instance[3]])
