#!/usr/bin/python3
import subprocess
from subprocess import PIPE
import sys
import os

print("Checking for changes in ", os.environ.get("COMMITS"))

result = subprocess.run("git diff --name-only $COMMITS | grep " + " ".join(sys.argv[1:]), shell=True, stdout=PIPE)
if not result.stdout:
   sys.exit("No changes")
