# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0001_squashed_0049_auto_20151223_1708'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubsidiaryInCampaign',
        ),
        migrations.AddField(
            model_name='team',
            name='name_with_members',
            field=models.TextField(editable=False, null=True),
        ),
    ]
