# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160531101208 on 2017-01-02 11:34
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.operations
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import dpnk.models.gpxfile
import dpnk.models.questionnaire


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:

class Migration(migrations.Migration):

    replaces = [('dpnk', '0002_auto_20160118_2004'), ('dpnk', '0003_tshirtsize_price'), ('dpnk', '0004_auto_20160216_1249'), ('dpnk', '0005_auto_20160216_1838'), ('dpnk', '0006_auto_20160217_1614'), ('dpnk', '0007_auto_20160219_1120'), ('dpnk', '0008_auto_20160224_1802'), ('dpnk', '0009_auto_20160224_1803'), ('dpnk', '0010_auto_20160225_1521'), ('dpnk', '0011_auto_20160227_1657'), ('dpnk', '0012_auto_20160227_1658'), ('dpnk', '0013_auto_20160227_1702'), ('dpnk', '0014_auto_20160302_2208'), ('dpnk', '0015_auto_20160303_1859'), ('dpnk', '0016_auto_20160305_1744'), ('dpnk', '0017_auto_20160314_1619'), ('dpnk', '0018_auto_20160327_0954'), ('dpnk', '0019_auto_20160327_1006'), ('dpnk', '0020_companyadmin_userprofile'), ('dpnk', '0021_auto_20160328_1115'), ('dpnk', '0022_auto_20160328_1129'), ('dpnk', '0023_userprofile_company_admin_count'), ('dpnk', '0024_auto_20160407_1827'), ('dpnk', '0025_auto_20160412_1238'), ('dpnk', '0026_auto_20160426_1420'), ('dpnk', '0027_auto_20160501_1112'), ('dpnk', '0028_auto_20160504_1304'), ('dpnk', '0029_auto_20160505_1218'), ('dpnk', '0030_choice_order'), ('dpnk', '0031_auto_20160531_1238'), ('dpnk', '0032_competition_show_results'), ('dpnk', '0033_auto_20160607_1132'), ('dpnk', '0034_auto_20160607_1346'), ('dpnk', '0035_competition_minimum_rides_base'), ('dpnk', '0036_auto_20160615_1317'), ('dpnk', '0037_auto_20160822_1022'), ('dpnk', '0038_campaign_has_any_tshirt'), ('dpnk', '0039_auto_20160825_1727'), ('dpnk', '0040_auto_20160825_1825'), ('dpnk', '0041_campaign_track_required')]

    dependencies = [
        ('dpnk', '0001_squashed_0049_auto_20151223_1708'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubsidiaryInCampaign',
        ),
        migrations.AddField(
            model_name='team',
            name='name_with_members',
            field=models.TextField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tshirtsize',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Cena'),
        ),
        migrations.DeleteModel(
            name='TeamInCampaign',
        ),
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ('-campaign', 'type', 'name'), 'verbose_name': 'Soutěžní kategorie', 'verbose_name_plural': 'Soutěžní kategorie'},
        ),
        migrations.AlterModelManagers(
            name='subsidiary',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='benefitial_admission_fee_company',
            field=models.FloatField(default=0, verbose_name='Benefiční startovné pro firmy'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_city',
            field=models.CharField(default='', help_text='Např. „Jablonec n. N.“ nebo „Praha 3, Žižkov“', max_length=50, verbose_name='Město'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_psc',
            field=models.IntegerField(default=None, help_text='Např.: „130 00“', null=True, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(10000)], verbose_name='PSČ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_recipient',
            field=models.CharField(blank=True, default='', help_text='Např. „odštěpný závod Brno“, „oblastní pobočka Liberec“, „Přírodovědecká fakulta“ atp.', max_length=50, null=True, verbose_name='Název pobočky (celé společnosti, závodu, kanceláře, fakulty) na adrese'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_street',
            field=models.CharField(default='', help_text='Např. „Šeříková“ nebo „Nám. W. Churchilla“', max_length=50, verbose_name='Ulice'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_street_number',
            field=models.CharField(default='', help_text='Např. „2965/12“ nebo „156“', max_length=10, verbose_name='Číslo domu'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Např. „Výrobna, a.s.“, „Příspěvková, p.o.“, „Nevládka, z.s.“, „Univerzita Karlova“', max_length=60, unique=True, verbose_name='Název společnosti'),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='address_city',
            field=models.CharField(default='', help_text='Např. „Jablonec n. N.“ nebo „Praha 3, Žižkov“', max_length=50, verbose_name='Město'),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='address_psc',
            field=models.IntegerField(default=None, help_text='Např.: „130 00“', null=True, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(10000)], verbose_name='PSČ'),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='address_recipient',
            field=models.CharField(blank=True, default='', help_text='Např. „odštěpný závod Brno“, „oblastní pobočka Liberec“, „Přírodovědecká fakulta“ atp.', max_length=50, null=True, verbose_name='Název pobočky (celé společnosti, závodu, kanceláře, fakulty) na adrese'),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='address_street',
            field=models.CharField(default='', help_text='Např. „Šeříková“ nebo „Nám. W. Churchilla“', max_length=50, verbose_name='Ulice'),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='address_street_number',
            field=models.CharField(default='', help_text='Např. „2965/12“ nebo „156“', max_length=10, verbose_name='Číslo domu'),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='city',
            field=models.ForeignKey(help_text="Rozhoduje o tom, do soutěží jakého města budete zařazeni a kde budete dostávat ceny - vizte <a href='http://www.dopracenakole.cz/pravidla' target='_blank'>pravidla soutěže</a>", on_delete=django.db.models.deletion.CASCADE, to='dpnk.City', verbose_name='Spádové město'),
        ),
        migrations.CreateModel(
            name='TeamInCampaign',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('dpnk.team',),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='personal_data_opt_in',
            field=models.BooleanField(default=False, verbose_name='Souhlas se zpracováním osobních údajů.'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company_pais_benefitial_fee',
            field=models.BooleanField(default=False, verbose_name='Moje firma si přeje podpořit Auto*Mat a zaplatit benefiční startovné.'),
        ),
        migrations.DeleteModel(
            name='TeamInCampaign',
        ),
        migrations.AddField(
            model_name='campaign',
            name='late_admission_phase',
            field=models.NullBooleanField(default=None, editable=False),
        ),
        migrations.AddField(
            model_name='userattendance',
            name='related_company_admin',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dpnk.CompanyAdmin'),
        ),
        migrations.AddField(
            model_name='userattendance',
            name='representative_payment',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dpnk.Payment'),
        ),
        migrations.CreateModel(
            name='TeamInCampaign',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('dpnk.team',),
        ),
        migrations.AddField(
            model_name='userattendance',
            name='frequency',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userattendance',
            name='has_unanswered_questionnaires',
            field=models.NullBooleanField(default=None, editable=False),
        ),
        migrations.AddField(
            model_name='userattendance',
            name='payment_status',
            field=models.CharField(choices=[('no_admission', 'neplatí se'), ('none', 'žádné platby'), ('done', 'zaplaceno'), ('waiting', 'nepotvrzeno'), ('unknown', 'neznámý')], editable=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userattendance',
            name='trip_length_total',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_count',
            field=models.IntegerField(db_index=True, default=None, editable=False, null=True, verbose_name='Počet právoplatných členů týmu'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Nová'), (2, 'Zrušena'), (7, 'Odmítnuta'), (4, 'Zahájena'), (5, 'Očekává potvrzení'), (7, 'Platba zamítnuta, prostředky nemožno vrátit, řeší PayU'), (99, 'Platba přijata'), (888, 'Nesprávný status -- kontaktovat PayU'), (1005, 'Platba akceptována firmou'), (1006, 'Faktura vystavena'), (1007, 'Faktura zaplacena'), (20001, 'Nový'), (20002, 'Přijat k sestavení'), (20003, 'Sestaven'), (20004, 'Odeslán'), (20005, 'Doručení potvrzeno'), (20006, 'Dosud nedoručeno'), (20007, 'Reklamován'), (40001, 'Oprava v cykloservisu'), (30002, 'Potvrzen vstup do soutěže')], default=0, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='trip',
            name='commute_mode',
            field=models.CharField(blank=True, choices=[('bicycle', 'Na kole'), ('by_foot', 'Pěšky/běh'), ('no_work', 'Nepracoval'), ('by_other_vehicle', 'Jiný dopravní prostředek')], default=None, max_length=20, null=True, verbose_name='Mód dopravy'),
        ),
        migrations.AddField(
            model_name='trip',
            name='direction',
            field=models.CharField(blank=True, choices=[('trip_to', 'Tam'), ('trip_from', 'Zpět')], max_length=20, null=True, verbose_name='Směr cesty'),
        ),
        migrations.AddField(
            model_name='trip',
            name='distance',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)], verbose_name='Ujetá vzdálenost'),
        ),
        migrations.AlterUniqueTogether(
            name='trip',
            unique_together=set([('user_attendance', 'date', 'direction')]),
        ),
        migrations.AlterField(
            model_name='userattendance',
            name='t_shirt_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dpnk.TShirtSize', verbose_name='Velikost trička'),
        ),
        migrations.RemoveField(
            model_name='trip',
            name='distance_from',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='distance_to',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='is_working_ride_from',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='is_working_ride_to',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_from',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_to',
        ),
        migrations.AlterField(
            model_name='gpxfile',
            name='trip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dpnk.Trip'),
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ('date', '-direction'), 'verbose_name': 'Cesta', 'verbose_name_plural': 'Cesty'},
        ),
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Datum cesty'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='distance',
            field=models.FloatField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)], verbose_name='Ujetá vzdálenost'),
        ),
        migrations.AlterModelOptions(
            name='companyadmin',
            options={'verbose_name': 'Koordinátor společnosti', 'verbose_name_plural': 'Koordinátoři společností'},
        ),
        migrations.AlterModelOptions(
            name='subsidiary',
            options={'verbose_name': 'Pobočka organizace', 'verbose_name_plural': 'Pobočky organizací'},
        ),
        migrations.AddField(
            model_name='companyadmin',
            name='will_pay_opt_in',
            field=models.BooleanField(default=False, verbose_name='Souhlas s platbou za zaměstnance.'),
        ),
        migrations.AlterField(
            model_name='cityincampaign',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cityincampaign', to='dpnk.City'),
        ),
        migrations.AlterField(
            model_name='companyadmin',
            name='administrated_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_admin', to='dpnk.Company', verbose_name='Koordinovaná společnost'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='competitor_type',
            field=models.CharField(choices=[('single_user', 'Jednotliví soutěžící'), ('liberos', 'Liberos'), ('team', 'Týmy'), ('company', 'Soutěž spoleností')], help_text='Určuje, zdali bude soutěž týmová, nebo pro jednotlivce. Ostatní volby vybírejte jen pokud víte, k čemu slouží.', max_length=16, verbose_name='Typ soutěžícího'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='user_attendance',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_trips', to='dpnk.UserAttendance'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mailing_hash',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Hash poslední synchronizace s mailingem'),
        ),
        migrations.AddField(
            model_name='team',
            name='unapproved_member_count',
            field=models.IntegerField(db_index=True, default=None, editable=False, null=True, verbose_name='Počet neschválených členů týmu'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='distance',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)], verbose_name='Ujetá vzdálenost'),
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('name',), 'verbose_name': 'Organizace', 'verbose_name_plural': 'Organizace'},
        ),
        migrations.AlterModelOptions(
            name='companyadmin',
            options={'verbose_name': 'Koordinátor organizace', 'verbose_name_plural': 'Koordinátoři organizací'},
        ),
        migrations.AlterField(
            model_name='campaign',
            name='admission_fee_company',
            field=models.FloatField(default=0, verbose_name='Včasné startovné pro organizace'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='benefitial_admission_fee_company',
            field=models.FloatField(default=0, verbose_name='Benefiční startovné pro organizace'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='late_admission_fee_company',
            field=models.FloatField(default=0, verbose_name='Pozdní startovné pro organizace'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='choice_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpnk.ChoiceType', verbose_name='Typ volby'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_recipient',
            field=models.CharField(blank=True, default='', help_text='Např. „odštěpný závod Brno“, „oblastní pobočka Liberec“, „Přírodovědecká fakulta“ atp.', max_length=50, null=True, verbose_name='Název pobočky (celé organizace, závodu, kanceláře, fakulty) na adrese'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Např. „Výrobna, a.s.“, „Příspěvková, p.o.“, „Nevládka, z.s.“, „Univerzita Karlova“', max_length=60, unique=True, verbose_name='Název organizace'),
        ),
        migrations.AlterField(
            model_name='companyadmin',
            name='administrated_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_admin', to='dpnk.Company', verbose_name='Koordinovaná organizace'),
        ),
        migrations.AlterField(
            model_name='companyadmin',
            name='will_pay_opt_in',
            field=models.BooleanField(default=False, verbose_name='Uživatel potvrdil, že bude plati za zaměstnance.'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dpnk.Company', verbose_name='Soutěž pouze pro organizace'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='company_competitors',
            field=models.ManyToManyField(blank=True, related_name='competitions', to='dpnk.Company', verbose_name='Přihlášené soutěžící organizace'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='competitor_type',
            field=models.CharField(choices=[('single_user', 'Jednotliví soutěžící'), ('liberos', 'Liberos'), ('team', 'Týmy'), ('company', 'Soutěž organizací')], help_text='Určuje, zdali bude soutěž týmová, nebo pro jednotlivce. Ostatní volby vybírejte jen pokud víte, k čemu slouží.', max_length=16, verbose_name='Typ soutěžícího'),
        ),
        migrations.AlterField(
            model_name='deliverybatch',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliverybatch_create', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='deliverybatch',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliverybatch_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='gpxfile',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gpxfile_create', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='gpxfile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gpxfile_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_create', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dpnk.Company', verbose_name='Organizace'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company_pais_benefitial_fee',
            field=models.BooleanField(default=False, verbose_name='Moje organizace si přeje podpořit Auto*Mat a zaplatit benefiční startovné.'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_type',
            field=models.CharField(blank=True, choices=[('mp', 'mPenize - mBank'), ('kb', 'MojePlatba'), ('rf', 'ePlatby pro eKonto'), ('pg', 'GE Money Bank'), ('pv', 'Sberbank (Volksbank)'), ('pf', 'Fio banka'), ('cs', 'PLATBA 24 – Česká spořitelna'), ('era', 'Era - Poštovní spořitelna'), ('cb', 'ČSOB'), ('c', 'Kreditní karta přes GPE'), ('bt', 'bankovní převod'), ('pt', 'převod přes poštu'), ('sc', 'superCASH'), ('psc', 'PaySec'), ('mo', 'Mobito'), ('t', 'testovací platba'), ('fa', 'faktura mimo PayU'), ('fc', 'organizace platí fakturou'), ('am', 'člen Klubu přátel Auto*Matu'), ('amw', 'kandidát na členství v Klubu přátel Auto*Matu'), ('fe', 'neplatí startovné')], max_length=50, null=True, verbose_name='Typ platby'),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='address_recipient',
            field=models.CharField(blank=True, default='', help_text='Např. „odštěpný závod Brno“, „oblastní pobočka Liberec“, „Přírodovědecká fakulta“ atp.', max_length=50, null=True, verbose_name='Název pobočky (celé organizace, závodu, kanceláře, fakulty) na adrese'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_create', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Nová'), (2, 'Zrušena'), (7, 'Odmítnuta'), (4, 'Zahájena'), (5, 'Očekává potvrzení'), (7, 'Platba zamítnuta, prostředky nemožno vrátit, řeší PayU'), (99, 'Platba přijata'), (888, 'Nesprávný status -- kontaktovat PayU'), (1005, 'Platba akceptována organizací'), (1006, 'Faktura vystavena'), (1007, 'Faktura zaplacena'), (20001, 'Nový'), (20002, 'Přijat k sestavení'), (20003, 'Sestaven'), (20004, 'Odeslán'), (20005, 'Doručení potvrzeno'), (20006, 'Dosud nedoručeno'), (20007, 'Reklamován'), (40001, 'Oprava v cykloservisu'), (30002, 'Potvrzen vstup do soutěže')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.AlterField(
            model_name='userattendance',
            name='track',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, geography=True, help_text='\n<ul>\n   <li><strong>Zadávání trasy zahájíte kliknutím na tlačítko "Nakreslit trasu", ukončíte kliknutím na cílový bod.</strong></li>\n   <li>Změnu trasy provedete po přepnutí do režimu úprav kliknutím na trasu.</li>\n   <li>Trasu stačí zadat tak, že bude zřejmé, kterými ulicemi vede.</li>\n   <li>Zadání přesnějšího průběhu nám však může pomoci lépe zjistit jak se lidé na kole pohybují.</li>\n   <li>Trasu bude možné změnit nebo upřesnit i později v průběhu soutěže.</li>\n   <li>Polohu začátku a konce trasy stačí zadávat s přesností 100m.</li>\n</ul>\nTrasa slouží k výpočtu vzdálenosti a pomůže nám lépe určit potřeby lidí pohybuících se ve městě na kole. Vaše cesta se zobrazí vašim týmovým kolegům.\n<br/>Trasy všech účastníků budou v anonymizované podobě zobrazené na úvodní stránce.\n', null=True, srid=4326, verbose_name='trasa'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('cs', 'Čeština'), ('en', 'Angličtna')], default='cs', help_text='Jazyk, ve kterém vám budou docházet emaily z registračního systému', max_length=16, verbose_name='Jazyk emailové komunikace'),
        ),
        migrations.AlterUniqueTogether(
            name='companyadmin',
            unique_together=set([('user', 'campaign')]),
        ),
        django.contrib.postgres.operations.UnaccentExtension(
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_type',
            field=models.CharField(blank=True, choices=[('mp', 'mPenize - mBank'), ('kb', 'MojePlatba'), ('rf', 'ePlatby pro eKonto'), ('pg', 'GE Money Bank'), ('pv', 'Sberbank (Volksbank)'), ('pf', 'Fio banka'), ('cs', 'PLATBA 24 – Česká spořitelna'), ('era', 'Era - Poštovní spořitelna'), ('cb', 'ČSOB'), ('c', 'Kreditní karta přes GPE'), ('bt', 'bankovní převod'), ('pt', 'převod přes poštu'), ('sc', 'superCASH'), ('psc', 'PaySec'), ('mo', 'Mobito'), ('uc', 'UniCredit'), ('t', 'testovací platba'), ('fa', 'faktura mimo PayU'), ('fc', 'organizace platí fakturou'), ('am', 'člen Klubu přátel Auto*Matu'), ('amw', 'kandidát na členství v Klubu přátel Auto*Matu'), ('fe', 'neplatí startovné')], max_length=50, null=True, verbose_name='Typ platby'),
        ),
        migrations.AddField(
            model_name='companyadmin',
            name='userprofile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_admin', to='dpnk.UserProfile', verbose_name='User profile'),
        ),
        migrations.AlterUniqueTogether(
            name='companyadmin',
            unique_together=set([('userprofile', 'campaign')]),
        ),
        migrations.AlterField(
            model_name='companyadmin',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_admin', to='dpnk.UserProfile', verbose_name='User profile'),
        ),
        migrations.RemoveField(
            model_name='companyadmin',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_admin_count',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='late_admission_phase',
        ),
        migrations.AlterField(
            model_name='company',
            name='dic',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='DIČ'),
        ),
        migrations.AlterField(
            model_name='companyadmin',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_admin', to='dpnk.UserProfile', verbose_name='Uživatelský profil'),
        ),
        migrations.AlterField(
            model_name='city',
            name='cyklistesobe_slug',
            field=models.SlugField(max_length=40, null=True, verbose_name='Jméno skupiny na webu Cyklisté sobě'),
        ),
        migrations.AddField(
            model_name='deliverybatch',
            name='dispatched',
            field=models.BooleanField(default=False, verbose_name='Vyřízeno'),
        ),
        migrations.AlterField(
            model_name='gpxfile',
            name='file',
            field=models.FileField(blank=True, help_text="Zadat trasu nahráním souboru GPX. Pro vytvoření GPX souboru s trasou můžete použít vyhledávání na naší <a href='http://mapa.prahounakole.cz/#hledani' target='_blank'>mapě</a>.", null=True, upload_to=dpnk.models.gpxfile.normalize_gpx_filename, verbose_name='GPX soubor'),
        ),
        migrations.AddField(
            model_name='team',
            name='frequency',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='commute_mode',
            field=models.CharField(blank=True, choices=[('bicycle', 'Kolo'), ('by_foot', 'Chůze/běh'), ('by_other_vehicle', 'Jinak'), ('no_work', 'Nijak/vůbec')], default=None, max_length=20, null=True, verbose_name='Mód dopravy'),
        ),
        migrations.AddField(
            model_name='gpxfile',
            name='ecc_last_upload',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datum posledního nahrátí do ECC'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ecc_email',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=128, unique=True, verbose_name='Email v ECC'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ecc_password',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=128, verbose_name='Heslo v ECC'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='commute_mode',
            field=models.CharField(blank=True, choices=[('bicycle', 'Kolo'), ('by_foot', 'Chůze/běh'), ('by_other_vehicle', 'Jinak'), ('no_work', 'Žádná cesta')], default=None, max_length=20, null=True, verbose_name='Mód dopravy'),
        ),
        migrations.AddField(
            model_name='choice',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ('order',), 'verbose_name': 'Nabídka k anketním otázce', 'verbose_name_plural': 'Nabídky k anketním otázkám'},
        ),
        migrations.AddField(
            model_name='answer',
            name='comment_given',
            field=models.TextField(blank=True, null=True, verbose_name='Hodnotitelský komentář'),
        ),
        migrations.AlterField(
            model_name='gpxfile',
            name='track',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, geography=True, help_text='\n<ul>\n   <li><strong>Zadávání trasy zahájíte kliknutím na tlačítko "Nakreslit trasu", ukončíte kliknutím na cílový bod.</strong></li>\n   <li>Změnu trasy provedete po přepnutí do režimu úprav kliknutím na trasu.</li>\n   <li>Trasu stačí zadat tak, že bude zřejmé, kterými ulicemi vede.</li>\n   <li>Zadání přesnějšího průběhu nám však může pomoci lépe zjistit jak se lidé na kole pohybují.</li>\n   <li>Trasu bude možné změnit nebo upřesnit i později v průběhu soutěže.</li>\n   <li>Polohu začátku a konce trasy stačí zadávat s přesností 100m.</li>\n</ul>\nTrasa slouží k výpočtu vzdálenosti a pomůže nám lépe určit potřeby lidí pohybuících se ve městě na kole. Vaše cesta se zobrazí vašim týmovým kolegům.\n<br/>Trasy všech účastníků budou v anonymizované podobě zobrazené na úvodní stránce.\n', null=True, srid=4326, verbose_name='trasa'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='type',
            field=models.CharField(choices=[('rekola', 'ReKola'), ('sportlife', 'SportLife')], default='rekola', max_length=10, verbose_name='typ voucheru'),
        ),
        migrations.AddField(
            model_name='competition',
            name='show_results',
            field=models.BooleanField(default=True, verbose_name='Zobrazovat výsledky soutěže'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='points_given',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('sequence_number', 'campaign'), 'verbose_name': 'Faktura', 'verbose_name_plural': 'Faktury'},
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='result_divident',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Dělenec'),
        ),
        migrations.AddField(
            model_name='competitionresult',
            name='result_divisor',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Dělitel'),
        ),
        migrations.AddField(
            model_name='competition',
            name='minimum_rides_base',
            field=models.PositiveIntegerField(default=28, help_text='Minimální počet jízd, které je nutné si zapsat, aby bylo možné dosáhnout 100% jízd', verbose_name='Minimální základ počtu jízd'),
        ),
        migrations.DeleteModel(
            name='TeamInCampaign',
        ),
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ('-campaign', 'name'), 'verbose_name': 'Soutěžní kategorie', 'verbose_name_plural': 'Soutěžní kategorie'},
        ),
        migrations.AddField(
            model_name='campaign',
            name='days_active',
            field=models.PositiveIntegerField(default=7, verbose_name='Počet minulých dní, které jdou zapisovat'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='attachment',
            field=models.FileField(blank=True, max_length=600, upload_to=dpnk.models.questionnaire.questionnaire_filename),
        ),
        migrations.DeleteModel(
            name='UserAttendanceRelated',
        ),
        migrations.CreateModel(
            name='TeamInCampaign',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('dpnk.team',),
        ),
        migrations.AlterField(
            model_name='trip',
            name='commute_mode',
            field=models.CharField(choices=[('bicycle', 'Kolo'), ('by_foot', 'Chůze/běh'), ('by_other_vehicle', 'Jinak'), ('no_work', 'Žádná cesta')], default=None, max_length=20, verbose_name='Mód dopravy'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='direction',
            field=models.CharField(choices=[('trip_to', 'Tam'), ('trip_from', 'Zpět')], default=None, max_length=20, verbose_name='Směr cesty'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='has_any_tshirt',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='language_prefixes',
            field=models.CharField(choices=[('dpnk', 'Do práce na kole'), ('dsnk', 'Do školy na kole')], default='dpnk', max_length=16, verbose_name='Jazyková sada'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='wp_api_url',
            field=models.URLField(blank=True, default='http://www.dopracenakole.cz/', null=True, verbose_name='Adresa pro Wordpress API se články'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='max_team_members',
            field=models.PositiveIntegerField(blank=True, default=5, null=True, verbose_name='Počet lidí v týmu'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='track_required',
            field=models.BooleanField(default=True, verbose_name='Je povinné zadávat trasu'),
        ),
    ]
