# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0006_auto_20160217_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInCampaign',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('dpnk.team',),
        ),
        migrations.AddField(
            model_name='userattendance',
            name='frequency',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userattendance',
            name='has_unanswered_questionnaires',
            field=models.NullBooleanField(default=None, editable=False),
        ),
        migrations.AddField(
            model_name='userattendance',
            name='payment_status',
            field=models.CharField(choices=[('no_admission', 'neplatí se'), ('none', 'žádné platby'), ('done', 'zaplaceno'), ('waiting', 'nepotvrzeno'), ('unknown', 'neznámý')], editable=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userattendance',
            name='trip_length_total',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_count',
            field=models.IntegerField(db_index=True, default=None, editable=False, null=True, verbose_name='Počet právoplatných členů týmu'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Nová'), (2, 'Zrušena'), (7, 'Odmítnuta'), (4, 'Zahájena'), (5, 'Očekává potvrzení'), (7, 'Platba zamítnuta, prostředky nemožno vrátit, řeší PayU'), (99, 'Platba přijata'), (888, 'Nesprávný status -- kontaktovat PayU'), (1005, 'Platba akceptována firmou'), (1006, 'Faktura vystavena'), (1007, 'Faktura zaplacena'), (20001, 'Nový'), (20002, 'Přijat k sestavení'), (20003, 'Sestaven'), (20004, 'Odeslán'), (20005, 'Doručení potvrzeno'), (20006, 'Dosud nedoručeno'), (20007, 'Reklamován'), (40001, 'Oprava v cykloservisu'), (30002, 'Potvrzen vstup do soutěže')], default=0, verbose_name='Status'),
        ),
    ]
