# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160321164524 on 2016-03-27 09:54
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0017_auto_20160314_1619'),
    ]

    operations = [
        UnaccentExtension()
    ]
