# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160321164524 on 2016-03-28 11:15
from __future__ import unicode_literals

from django.db import migrations

def copy_userprofile(apps, schema_editor):
    CompanyAdmin  = apps.get_model("dpnk", "CompanyAdmin")
    for ca in CompanyAdmin.objects.all():
        ca.userprofile = ca.user.userprofile
        ca.save()

#def copy_user(apps, schema_editor):
#    CompanyAdmin  = apps.get_model("dpnk", "CompanyAdmin")
#    for ca in CompanyAdmin.objects.all():
#        ca.user = ca.userprofile.user
#        ca.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0020_companyadmin_userprofile'),
    ]

    operations = [
        migrations.RunPython(copy_userprofile)#, reverse_code=copy_user),
    ]
