# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160321164524 on 2016-05-04 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0027_auto_20160501_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxfile',
            name='ecc_last_upload',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datum posledního nahrátí do ECC'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ecc_email',
            field=models.CharField(blank=True, db_index=True, default='HPH2AqNE3h@dopracenakole.cz', max_length=128, null=True, verbose_name='Heslo v ECC'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ecc_password',
            field=models.CharField(blank=True, db_index=True, default='YhjFF6H23X', max_length=128, null=True, verbose_name='Heslo v ECC'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='commute_mode',
            field=models.CharField(blank=True, choices=[('bicycle', 'Kolo'), ('by_foot', 'Chůze/běh'), ('by_other_vehicle', 'Jinak'), ('no_work', 'Žádná cesta')], default=None, max_length=20, null=True, verbose_name='Mód dopravy'),
        ),
    ]
