# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160321164524 on 2016-05-05 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0028_auto_20160504_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ecc_email',
            field=models.CharField(db_index=True, default=None, max_length=128, unique=True, verbose_name='Heslo v ECC'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ecc_password',
            field=models.CharField(db_index=True, default=None, max_length=128, verbose_name='Email v ECC'),
        ),
    ]
