# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160531101208 on 2016-06-08 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0034_auto_20160607_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='minimum_rides_base',
            field=models.PositiveIntegerField(default=28, help_text='Minimální počet jízd, které je nutné si zapsat, aby bylo možné dosáhnout 100% jízd', verbose_name='Minimální základ počtu jízd'),
        ),
    ]
