# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160531101208 on 2016-06-15 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import dpnk.models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0035_competition_minimum_rides_base'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamInCampaign',
        ),
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ('-campaign', 'name'), 'verbose_name': 'Soutěžní kategorie', 'verbose_name_plural': 'Soutěžní kategorie'},
        ),
        migrations.AddField(
            model_name='campaign',
            name='days_active',
            field=models.PositiveIntegerField(default=7, verbose_name='Počet minulých dní, které jdou zapisovat'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='attachment',
            field=models.FileField(blank=True, max_length=600, upload_to=dpnk.models.questionnaire_filename),
        ),
    ]
