# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160531101208 on 2016-08-22 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0036_auto_20160615_1317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAttendanceRelated',
        ),
        migrations.CreateModel(
            name='TeamInCampaign',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('dpnk.team',),
        ),
        migrations.AlterField(
            model_name='trip',
            name='commute_mode',
            field=models.CharField(choices=[('bicycle', 'Kolo'), ('by_foot', 'Chůze/běh'), ('by_other_vehicle', 'Jinak'), ('no_work', 'Žádná cesta')], default=None, max_length=20, verbose_name='Mód dopravy'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='direction',
            field=models.CharField(choices=[('trip_to', 'Tam'), ('trip_from', 'Zpět')], default=None, max_length=20, verbose_name='Směr cesty'),
        ),
    ]
