# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160531101208 on 2016-09-14 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0040_auto_20160825_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='track_required',
            field=models.BooleanField(default=True, verbose_name='Je povinné zadávat trasu'),
        ),
    ]
