# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160531101208 on 2017-01-26 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0048_auto_20170106_1948'),
    ]

    database_operations = [
        migrations.AlterModelTable('DeliveryBatch', 't_shirt_delivery'),
        migrations.AlterModelTable('PackageTransaction', 't_shirt_delivery'),
        migrations.AlterModelTable('TShirtSize', 't_shirt_delivery'),
        migrations.AlterField(
            model_name='userattendance',
            name='t_shirt_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_shirt_delivery.TShirtSize', verbose_name='Velikost trička'),
        ),
    ]

    state_operations = [
		migrations.DeleteModel('DeliveryBatch'),
		migrations.DeleteModel('PackageTransaction'),
		migrations.DeleteModel('TShirtSize'),
	]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations,
		)
    ]
