# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160531101208 on 2017-01-26 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0049_auto_20170113_1552'),
    ]

    database_operations = [
        migrations.AlterModelTable('DeliveryBatch', 't_shirt_delivery_deliverybatch'),
        migrations.AlterModelTable('PackageTransaction', 't_shirt_delivery_packagetransaction'),
        migrations.AlterModelTable('TShirtSize', 't_shirt_delivery_tshirtsize'),
    ]

    state_operations = [
		migrations.DeleteModel('DeliveryBatch'),
		migrations.DeleteModel('PackageTransaction'),
		migrations.DeleteModel('TShirtSize'),
	]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations,
		),
    ]
