# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160531101208 on 2017-01-26 15:22
from __future__ import unicode_literals

import django
from django.db import migrations, models


def rename_content_types(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    ContentType.objects.filter(model='packagetransaction').update(app_label='t_shirt_size')


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0049_auto_20170113_1552'),
    ]

    database_operations = [
        migrations.AlterModelTable('DeliveryBatch', 't_shirt_delivery_deliverybatch'),
        migrations.AlterModelTable('PackageTransaction', 't_shirt_delivery_packagetransaction'),
        migrations.AlterModelTable('TShirtSize', 't_shirt_delivery_tshirtsize'),
		migrations.AlterField(
			model_name='userattendance',
			name='t_shirt_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='t_shirt_delivery.TShirtSize', verbose_name='Velikost trička'),
		)
    ]

    state_operations = [
		migrations.DeleteModel('DeliveryBatch'),
		migrations.DeleteModel('PackageTransaction'),
		migrations.DeleteModel('TShirtSize'),
		migrations.AlterField(
			model_name='userattendance',
			name='t_shirt_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='t_shirt_delivery.TShirtSize', verbose_name='Velikost trička'),
		)
	]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations,
		),
        migrations.RunPython(rename_content_types),
    ]
