# -*- coding: utf-8 -*-
# Generated by Django 1.9.5.dev20160531101208 on 2017-01-31 16:29
from __future__ import unicode_literals

from django.db import migrations


def rename_content_types(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    import pudb; pudb.set_trace()
    raise Exception()



class Migration(migrations.Migration):

    dependencies = [
        ('t_shirt_delivery', '0002_auto_20170130_0343'),
        ('dpnk', '0050_move_models_to_t_shirt_delivery')
    ]

    operations = [
        migrations.RunPython(rename_content_types),
    ]
