# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-07 08:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0051_auto_20170219_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Název povolání')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Povolání',
                'ordering': ['order'],
                'verbose_name': 'Povolání',
            },
        ),
        migrations.DeleteModel(
            name='UserAttendanceToBatch',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age_group',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ročník'),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='city',
            field=models.ForeignKey(help_text="Vyberte nejbližší soutěžní město. Vaše pobočka bude zařazena do žebříčků za vybrané město a případnou výhru si přeberete na závěrečném večírku pořádaném tímto městem. Sledujte  <a href='http://www.dopracenakole.cz/pravidla' target='_blank'>pravidla soutěže</a> svého města.", on_delete=django.db.models.deletion.CASCADE, to='dpnk.City', verbose_name='Spádové město'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='occupation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dpnk.Occupation', verbose_name='Povolání'),
        ),
    ]
