# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-19 10:17
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0052_auto_20170307_0810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyadmin',
            options={'verbose_name': 'Firemní koordinátor', 'verbose_name_plural': 'Firemní koordinátoři'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['user__last_name', 'user__first_name'], 'permissions': (('can_edit_all_cities', 'Může editovat všechna města'),), 'verbose_name': 'Uživatelský profil', 'verbose_name_plural': 'Uživatelské profily'},
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='box_addressee_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email adresáta krabice pro tým'),
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='box_addressee_name',
            field=models.CharField(blank=True, help_text='Jmené osoby, která převezme krabici s tričky a zajistí jeich rozdělení na této pobočce. Nemusí se účastnit soutěže.', max_length=30, null=True, verbose_name='Jméno adresáta krabice pro tým'),
        ),
        migrations.AddField(
            model_name='subsidiary',
            name='box_addressee_telephone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefon adresáta krabice pro tým'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='email_footer',
            field=models.TextField(blank=True, default='', max_length=5000, null=True, verbose_name='Patička uživatelských e-mailů'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_recipient',
            field=models.CharField(blank=True, default='', help_text='Např. „odštěpný závod Brno“, „oblastní pobočka Liberec“, „Přírodovědecká fakulta“ atp. Nemá-li vaše organizace pobočky, pak nechte pole prázdné.', max_length=50, null=True, verbose_name='Název pobočky (závodu, kanceláře, fakulty), nepovinné pole'),
        ),
        migrations.AlterField(
            model_name='companyadmin',
            name='company_admin_approved',
            field=models.CharField(choices=[('approved', 'Odsouhlasený'), ('undecided', 'Nerozhodnuto'), ('denied', 'Zamítnutý')], default='undecided', max_length=16, verbose_name='Schválena funkce firemního koordinátora'),
        ),
        migrations.AlterField(
            model_name='companyadmin',
            name='motivation_company_admin',
            field=models.TextField(blank=True, default='', help_text='Napište nám prosím, jakou zastáváte u vašeho zaměstnavatele pozici', max_length=5000, null=True, verbose_name='Zaměstnanecká pozice'),
        ),
        migrations.AlterField(
            model_name='gpxfile',
            name='track',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, geography=True, help_text='\n<ul>\n   <li><strong>Zadávání trasy zahájíte kliknutím na tlačítko <span style="display: inline-block;" class="leaflet-draw-toolbar leaflet-bar leaflet-draw-toolbar-top"><a class="leaflet-draw-draw-polyline" href="#"></a></span>, ukončíte kliknutím na cílový bod.</strong></li>\n   <li>Změnu trasy provedete po přepnutí do režimu úprav (<span style="display: inline-block;" class="leaflet-draw-toolbar leaflet-bar"><a class="leaflet-draw-edit-edit" href="#"></a></span>) kliknutím na trasu.</li>\n   <li>Trasu stačí zadat tak, že bude zřejmé, kterými ulicemi vede.</li>\n   <li>Zadání přesnějšího průběhu nám však může pomoci lépe zjistit, jak se lidé na kole pohybují.</li>\n   <li>Trasu bude možné změnit nebo upřesnit i později v průběhu soutěže.</li>\n   <li>Polohu začátku a konce trasy stačí zadávat se 100m přesností.</li>\n</ul>\nTrasa slouží k výpočtu vzdálenosti a pomůže nám lépe určit potřeby lidí pohybuících se ve městě na kole. Vaše cesta se zobrazí vašim týmovým kolegům.\n<br/>Trasy všech účastníků budou v anonymizované podobě zobrazené na úvodní stránce.\n', null=True, srid=4326, verbose_name='trasa'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_type',
            field=models.CharField(blank=True, choices=[('mp', 'mPenize - mBank'), ('kb', 'MojePlatba'), ('rf', 'ePlatby pro eKonto'), ('pg', 'GE Money Bank'), ('pv', 'Sberbank (Volksbank)'), ('pf', 'Fio banka'), ('cs', 'PLATBA 24 – Česká spořitelna'), ('era', 'Era - Poštovní spořitelna'), ('cb', 'ČSOB'), ('c', 'Kreditní karta přes GPE'), ('bt', 'bankovní převod'), ('pt', 'převod přes poštu'), ('sc', 'superCASH'), ('psc', 'PaySec'), ('mo', 'Mobito'), ('uc', 'UniCredit'), ('t', 'testovací platba'), ('fa', 'faktura mimo PayU'), ('fc', 'organizace platí fakturou'), ('am', 'člen Klubu přátel Auto*Matu'), ('amw', 'kandidát na členství v Klubu přátel Auto*Matu'), ('fe', 'neplatí účastnický poplatek ')], max_length=50, null=True, verbose_name='Typ platby'),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='address_recipient',
            field=models.CharField(blank=True, default='', help_text='Např. „odštěpný závod Brno“, „oblastní pobočka Liberec“, „Přírodovědecká fakulta“ atp. Nemá-li vaše organizace pobočky, pak nechte pole prázdné.', max_length=50, null=True, verbose_name='Název pobočky (závodu, kanceláře, fakulty), nepovinné pole'),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='city',
            field=models.ForeignKey(help_text="Vyberte nejbližší soutěžní město. Vaše pobočka bude zařazena do žebříčků za vybrané město a případnou výhru si přeberete na závěrečném večírku pořádaném tímto městem. Sledujte <a href='http://www.dopracenakole.cz/pravidla' target='_blank'>pravidla soutěže</a> svého města.", on_delete=django.db.models.deletion.CASCADE, to='dpnk.City', verbose_name='Spádové město'),
        ),
        migrations.AlterField(
            model_name='userattendance',
            name='t_shirt_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='t_shirt_delivery.TShirtSize', verbose_name='Velikost trika'),
        ),
        migrations.AlterField(
            model_name='userattendance',
            name='track',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, geography=True, help_text='\n<ul>\n   <li><strong>Zadávání trasy zahájíte kliknutím na tlačítko <span style="display: inline-block;" class="leaflet-draw-toolbar leaflet-bar leaflet-draw-toolbar-top"><a class="leaflet-draw-draw-polyline" href="#"></a></span>, ukončíte kliknutím na cílový bod.</strong></li>\n   <li>Změnu trasy provedete po přepnutí do režimu úprav (<span style="display: inline-block;" class="leaflet-draw-toolbar leaflet-bar"><a class="leaflet-draw-edit-edit" href="#"></a></span>) kliknutím na trasu.</li>\n   <li>Trasu stačí zadat tak, že bude zřejmé, kterými ulicemi vede.</li>\n   <li>Zadání přesnějšího průběhu nám však může pomoci lépe zjistit, jak se lidé na kole pohybují.</li>\n   <li>Trasu bude možné změnit nebo upřesnit i později v průběhu soutěže.</li>\n   <li>Polohu začátku a konce trasy stačí zadávat se 100m přesností.</li>\n</ul>\nTrasa slouží k výpočtu vzdálenosti a pomůže nám lépe určit potřeby lidí pohybuících se ve městě na kole. Vaše cesta se zobrazí vašim týmovým kolegům.\n<br/>Trasy všech účastníků budou v anonymizované podobě zobrazené na úvodní stránce.\n', null=True, srid=4326, verbose_name='trasa'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age_group',
            field=models.PositiveIntegerField(blank=True, choices=[(2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980), (1979, 1979), (1978, 1978), (1977, 1977), (1976, 1976), (1975, 1975), (1974, 1974), (1973, 1973), (1972, 1972), (1971, 1971), (1970, 1970), (1969, 1969), (1968, 1968), (1967, 1967), (1966, 1966), (1965, 1965), (1964, 1964), (1963, 1963), (1962, 1962), (1961, 1961), (1960, 1960), (1959, 1959), (1958, 1958), (1957, 1957), (1956, 1956), (1955, 1955), (1954, 1954), (1953, 1953), (1952, 1952), (1951, 1951), (1950, 1950), (1949, 1949), (1948, 1948), (1947, 1947), (1946, 1946), (1945, 1945), (1944, 1944), (1943, 1943), (1942, 1942), (1941, 1941), (1940, 1940), (1939, 1939), (1938, 1938), (1937, 1937), (1936, 1936), (1935, 1935), (1934, 1934), (1933, 1933), (1932, 1932), (1931, 1931), (1930, 1930), (1929, 1929), (1928, 1928), (1927, 1927), (1926, 1926), (1925, 1925), (1924, 1924), (1923, 1923), (1922, 1922), (1921, 1921), (1920, 1920), (1919, 1919), (1918, 1918)], help_text='Nepovinné, slouží pouze pro účely statistky', null=True, verbose_name='Ročník narození'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ecc_email',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=128, unique=True, verbose_name='E-mail v ECC'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(choices=[('cs', 'Čeština'), ('en', 'Angličtna')], default='cs', help_text='V tomto jazyce vám budou přicházet e-maily z registračního systému', max_length=16, verbose_name='Jazyk e-mailové komunikace'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mailing_opt_in',
            field=models.NullBooleanField(default=None, help_text='Odběr e-mailů můžete kdykoliv v průběhu soutěže zrušit.', verbose_name='Přeji si dostávat e-mailem informace o akcích, událostech a dalších záležitostech souvisejících se soutěží.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='occupation',
            field=models.ForeignKey(blank=True, help_text='Nepovinné, bude použito pro účely žebříčků dle jednotlivých profesí', null=True, on_delete=django.db.models.deletion.CASCADE, to='dpnk.Occupation', verbose_name='Profese'),
        ),
    ]
