# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-06 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0056_auto_20170331_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='wp_slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Subdoména na WordPressu'),
        ),
        migrations.AlterField(
            model_name='userattendance',
            name='discount_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons.DiscountCoupon', verbose_name='Slevový kupón'),
        ),
        migrations.AlterField(
            model_name='userattendance',
            name='t_shirt_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='t_shirt_delivery.TShirtSize', verbose_name='Velikost trika'),
        ),
        migrations.AlterField(
            model_name='userattendance',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='dpnk.Team', verbose_name='Tým'),
        ),
    ]
