# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-06 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0057_auto_20170406_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='wp_slug',
            field=models.SlugField(blank=True, help_text='Pokud není vyplněno, použije se slug', null=True, unique=True, verbose_name='Subdoména na WordPressu'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='variable_symbol',
            field=models.CharField(blank=True, help_text='Variabilní symbol faktury', max_length=255, null=True, unique=True, verbose_name='Variabilní symbol'),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='box_addressee_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email adresáta krabice pro pobočku'),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='box_addressee_name',
            field=models.CharField(blank=True, help_text='Jmené osoby, která převezme krabici s tričky a zajistí jeich rozdělení na této pobočce. Nemusí se účastnit soutěže.', max_length=30, null=True, verbose_name='Jméno adresáta krabice pro pobočku'),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='box_addressee_telephone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefon adresáta krabice pro pobočku'),
        ),
    ]
