# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-12 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0058_auto_20170406_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxfile',
            name='distance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Vzdálenost v metrech'),
        ),
        migrations.AddField(
            model_name='gpxfile',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Doba v sekundách'),
        ),
        migrations.AddField(
            model_name='gpxfile',
            name='source_application',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Zdrojová aplikace'),
        ),
    ]
