# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0068_auto_20170512_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='commute_mode_choice',
            new_name='commute_mode',
        ),
    ]
