# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0072_gpxfile_commute_mode_remove'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpxfile',
            old_name='commute_mode_choice',
            new_name='commute_mode',
        ),
    ]
