# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 12:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0079_auto_20170725_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='wp_api_date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Datum, od kterého se zobrazují příspěvky z Wordpress API se články'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ico',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Pokud má vaše organizace IČO, prosím vyplňte, jinak nechte prázdné.', null=True, verbose_name='IČO'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='phase_type',
            field=models.CharField(choices=[('registration', 'registrační'), ('payment', 'placení startovného'), ('competition', 'soutěžní'), ('results', 'výsledková'), ('admissions', 'přihlašovací do soutěží'), ('invoices', 'vytváření faktur')], default='registration', max_length=16, verbose_name='Typ fáze'),
        ),
        migrations.AlterField(
            model_name='team',
            name='invitation_token',
            field=models.CharField(default='', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(25)], verbose_name='Token pro pozvánky'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mailing_opt_in',
            field=models.NullBooleanField(default=None, help_text='Odběr e-mailů můžete kdykoliv v průběhu soutěže zrušit.', verbose_name='Soutěžní e-maily'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(help_text='Telefonní číslo slouží jako kontakt pro help desk.', max_length=30, validators=[django.core.validators.RegexValidator('^[0-9+ ]*$', 'Telefon musí být složen s čísel, mezer a znaku plus.'), django.core.validators.MinLengthValidator(9)], verbose_name='Telefon'),
        ),
    ]
