# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 22:41
from __future__ import unicode_literals

from django.db import migrations


def populate_personal_opt_in(apps, schema_editor):
    UserAttendance = apps.get_model("dpnk", "UserAttendance")

    for user_attendance in UserAttendance.objects.all():
        user_attendance.personal_data_opt_in = user_attendance.userprofile.personal_data_opt_in
        user_attendance.save()

    DirtyInstance = apps.get_model("denorm", "DirtyInstance")
    DirtyInstance.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0081_auto_20170831_2232'),
    ]

    operations = [
        migrations.RunPython(populate_personal_opt_in),
    ]
