# Generated by Django 2.0.2 on 2018-03-16 10:19

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0091_auto_20180307_1214'),
    ]

    operations = [
        TrigramExtension(),
    ]
