# Generated by Django 2.0.3 on 2018-04-15 12:40

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import dpnk.models.trip


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dpnk', '0094_auto_20180413_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_create', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='trip',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Datum vytvoření'),
        ),
        migrations.AddField(
            model_name='trip',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Doba v sekundách'),
        ),
        migrations.AddField(
            model_name='trip',
            name='from_application',
            field=models.BooleanField(default=False, verbose_name='Nahráno z aplikace'),
        ),
        migrations.AddField(
            model_name='trip',
            name='source_application',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Zdrojová aplikace'),
        ),
        migrations.AddField(
            model_name='trip',
            name='gpx_file',
            field=models.FileField(blank=True, help_text="Zadat trasu nahráním souboru GPX. Pro vytvoření GPX souboru s trasou můžete použít vyhledávání na naší <a href='https://mapa.prahounakole.cz/#hledani' target='_blank'>mapě</a>.", max_length=512, null=True, upload_to=dpnk.models.trip.normalize_gpx_filename, verbose_name='GPX soubor'),
        ),
        migrations.AddField(
            model_name='trip',
            name='source_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Identifikátor v původní aplikaci'),
        ),
        migrations.AddField(
            model_name='trip',
            name='track',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(geography=True, help_text='\n<ul>\n   <li><strong>Zadávání trasy zahájíte kliknutím na tlačítko <span style="display: inline-block;" class="leaflet-draw-toolbar leaflet-bar leaflet-draw-toolbar-top"><a class="leaflet-draw-draw-polyline" href="#"></a></span>.</strong></li>\n   <li>Další body zadáváte kliknutím do mapy, <strong>cílový bod zadáte dvouklikem.</strong></li>\n   <li>Změnu trasy provedete po přepnutí do režimu úprav (<span style="display: inline-block;" class="leaflet-draw-toolbar leaflet-bar"><a class="leaflet-draw-edit-edit" href="#"></a></span>) kliknutím na trasu.</li>\n   <li>Trasu stačí zadat tak, že bude zřejmé, kterými ulicemi vede.\n   (Zadání přesnějšího průběhu nám však může pomoci lépe zjistit, jak se lidé na kole pohybují.)</li>\n   <li>Trasu bude možné změnit nebo upřesnit i později v průběhu soutěže.\n   (Trasy za jednotlivé dny však jen 7 dní nazpět.)</li>\n   <li>Polohu začátku a konce trasy stačí zadávat se 100m přesností.</li>\n</ul>\nTrasa slouží k výpočtu vzdálenosti a pomůže nám lépe určit potřeby lidí pohybuících se ve městě na kole.\n<br/>Trasy všech účastníků budou v anonymizované podobě zobrazené na <a href="https://mapa.prahounakole.cz/?zoom=13&lat=50.08741&lon=14.4211&layers=_Wgt">mapě Prahou na kole</a>.\n', null=True, srid=4326, verbose_name='trasa'),
        ),
        migrations.AddField(
            model_name='trip',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Datum poslední změny'),
        ),
        migrations.AddField(
            model_name='trip',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
    ]
