# Generated by Django 2.0.4 on 2018-04-30 11:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0098_auto_20180428_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='date_from',
            field=models.DateField(default=None, help_text='Od tohoto data (včetně) se počítají jízdy a je možné vyplňovat dotazník', null=True, verbose_name='Datum začátku soutěže'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='date_to',
            field=models.DateField(default=None, help_text='Do tohoto data (včetně) se počítají jízdy a je možné vyplňovat dotazník', null=True, verbose_name='Datum konce soutěže'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='distance',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)], verbose_name='Ujetá vzdálenost (km)'),
        ),
    ]
