# Generated by Django 2.0.4 on 2018-05-14 15:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0099_auto_20180430_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client_note',
            field=models.TextField(blank=True, default='', max_length=255, verbose_name='Poznámka k adresátovi'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='country',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Země'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_recipient',
            field=models.CharField(blank=True, default='', help_text='Např. „odštěpný závod Brno“, „oblastní pobočka Liberec“, „Přírodovědecká fakulta“ atp. Nemá-li vaše organizace pobočky, pak nechte pole prázdné.', max_length=50, null=True, verbose_name='Adresát na faktuře'),
        ),
        migrations.AlterField(
            model_name='gpxfile',
            name='track',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, geography=True, help_text='\n<br/>\n<strong><a href="/help/" target="_blank">Klikněte zde pro nápovědu k editaci tras.</a></strong>\n<br/>\n\nTrasa slouží k výpočtu vzdálenosti a pomůže nám lépe určit potřeby lidí pohybujících se ve městě na kole.\n<br/>Trasy všech účastníků budou v anonymizované podobě zobrazené na <a href="https://mapa.prahounakole.cz/?zoom=13&lat=50.08741&lon=14.4211&layers=_Wgt">mapě Prahou na kole</a>.\n', null=True, srid=4326, verbose_name='trasa'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company_address_psc',
            field=models.CharField(blank=True, help_text='Např.: „130 00“', max_length=50, null=True, verbose_name='PSČ'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company_address_recipient',
            field=models.CharField(blank=True, default='', help_text='Např. „odštěpný závod Brno“, „oblastní pobočka Liberec“, „Přírodovědecká fakulta“ atp. Nemá-li vaše organizace pobočky, pak nechte pole prázdné.', max_length=50, null=True, verbose_name='Adresát na faktuře'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='track',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, geography=True, help_text='\n<br/>\n<strong><a href="/help/" target="_blank">Klikněte zde pro nápovědu k editaci tras.</a></strong>\n<br/>\n\nTrasa slouží k výpočtu vzdálenosti a pomůže nám lépe určit potřeby lidí pohybujících se ve městě na kole.\n<br/>Trasy všech účastníků budou v anonymizované podobě zobrazené na <a href="https://mapa.prahounakole.cz/?zoom=13&lat=50.08741&lon=14.4211&layers=_Wgt">mapě Prahou na kole</a>.\n', null=True, srid=4326, verbose_name='trasa'),
        ),
        migrations.AlterField(
            model_name='userattendance',
            name='track',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, geography=True, help_text='\n<br/>\n<strong><a href="/help/" target="_blank">Klikněte zde pro nápovědu k editaci tras.</a></strong>\n<br/>\n\nTrasa slouží k výpočtu vzdálenosti a pomůže nám lépe určit potřeby lidí pohybujících se ve městě na kole.\n<br/>Trasy všech účastníků budou v anonymizované podobě zobrazené na <a href="https://mapa.prahounakole.cz/?zoom=13&lat=50.08741&lon=14.4211&layers=_Wgt">mapě Prahou na kole</a>.\n', null=True, srid=4326, verbose_name='trasa'),
        ),
    ]
