# Generated by Django 2.0.3 on 2018-05-27 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smmapdfs', '0001_initial'),
        ('dpnk', '0102_auto_20180518_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('pdfsandwichabc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='smmapdfs.PdfSandwichABC')),
            ],
            bases=('smmapdfs.pdfsandwichabc',),
        ),
        migrations.CreateModel(
            name='DiplomaField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(default=None, max_length=36, verbose_name='field')),
                ('font_size', models.IntegerField(default=16, verbose_name='Font size')),
                ('x', models.IntegerField(default=0, verbose_name='X (mm)')),
                ('y', models.IntegerField(default=0, verbose_name='Y (mm)')),
                ('font', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smmapdfs.PdfSandwichFont')),
                ('pdfsandwich_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdfsandwich_fields', to='smmapdfs.PdfSandwichType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ('-campaign', '-priority', 'name'), 'verbose_name': 'Soutěžní kategorie', 'verbose_name_plural': 'Soutěžní kategorie'},
        ),
        migrations.AddField(
            model_name='campaign',
            name='sandwich_type',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='smmapdfs.PdfSandwichType'),
        ),
        migrations.AlterField(
            model_name='userattendance',
            name='last_sync_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Poslední synchronizace'),
        ),
        migrations.AddField(
            model_name='diploma',
            name='obj',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dpnk.UserAttendance'),
        ),
    ]
