# Generated by Django 2.0.3 on 2018-07-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0105_auto_20180612_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diplomafield',
            name='alignment',
        ),
        migrations.AddField(
            model_name='campaign',
            name='tracks',
            field=models.BooleanField(default=True, verbose_name='Uloží se trasu'),
        ),
    ]
