# Generated by Django 2.0.3 on 2018-07-30 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0106_auto_20180726_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='recreational',
            field=models.BooleanField(default=False, verbose_name='Lze zadávat i výlety'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='direction',
            field=models.CharField(choices=[('trip_to', 'Tam'), ('trip_from', 'Zpět'), ('recreational', 'Výlet')], default=None, max_length=20, verbose_name='Směr cesty'),
        ),
    ]
