# Generated by Django 2.0.3 on 2018-08-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0107_auto_20180730_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattendance',
            name='recreational_trip_length',
            field=models.FloatField(editable=False, null=True),
        ),
    ]
