# Generated by Django 2.0.3 on 2018-08-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0108_userattendance_recreational_trip_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userattendance',
            old_name='recreational_trip_length',
            new_name='total_trip_length_including_recreational',
        ),
    ]
