# Generated by Django 2.0.3 on 2018-08-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0109_auto_20180801_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='recreational',
            field=models.BooleanField(default=False, verbose_name='Započítá se i rekreační jízdy?'),
        ),
    ]
