# Generated by Django 2.0.8 on 2018-11-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0119_auto_20180824_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dont_show_name',
            field=models.BooleanField(default=False, verbose_name='Nezobrazovat skutečné jméno veřejně'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='mailing_list_enabled',
            field=models.NullBooleanField(default=None, unique=True, verbose_name='Povolit mailing list'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('male', 'Muž'), ('female', 'Žena')], help_text='Slouží k zařazení do výkonnostních kategorií', max_length=50, verbose_name='Pohlaví'),
        ),
    ]
