# Generated by Django 2.1.3 on 2018-11-28 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0120_auto_20181120_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsidiary',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsidiaries', to='dpnk.Company'),
        ),
    ]
