# Generated by Django 2.0.9 on 2019-02-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0123_auto_20190115_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='mailing_list_type',
            field=models.CharField(blank=True, choices=[(None, 'Disabled'), ('campaign_monitor', 'Campaign monitor'), ('ecomail', 'EcoMail')], default=None, max_length=60, null=True, verbose_name='ID mailing listu'),
        ),
        migrations.AlterUniqueTogether(
            name='campaign',
            unique_together={('mailing_list_type', 'mailing_list_id')},
        ),
    ]
