# Generated by Django 2.0.13 on 2019-02-27 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0011_auto_20190227_1150'),
        ('dpnk', '0124_auto_20190220_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Gallery', verbose_name='Galerie týmových fotek'),
        ),
    ]
