# Generated by Django 2.0.13 on 2019-03-10 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0125_team_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Jméno typu kampaně')),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='year',
            field=models.CharField(default=2019, max_length=60, verbose_name='Ročník kampaně'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Muž'), ('female', 'Žena')], default=None, help_text='Tato informace se nám bude hodit při rozřazování do výkonnostních kategorií.', max_length=50, null=True, verbose_name='Pohlaví'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dpnk.CampaignType', verbose_name='Typ kampaně'),
        ),
        migrations.AlterUniqueTogether(
            name='campaign',
            unique_together={('mailing_list_type', 'mailing_list_id'), ('campaign_type', 'year')},
        ),
    ]
