# Generated by Django 2.0.13 on 2019-03-10 11:56

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0126_auto_20190310_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='main_color',
            field=colorfield.fields.ColorField(default='#1EA04F', max_length=18, verbose_name='Hlavní barva kampaně'),
        ),
    ]
