# Generated by Django 2.0.9 on 2019-04-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0130_commutemode_icon_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=512, upload_to='', verbose_name='Landing page image')),
                ('role', models.CharField(choices=[('main', 'Hlavní obráz')], max_length=64, verbose_name='Role pro obráz')),
                ('min_frequency', models.FloatField(blank=True, null=True, verbose_name='Min pravidelnost')),
                ('max_frequency', models.FloatField(blank=True, null=True, verbose_name='Max pravidelnost')),
            ],
        ),
    ]
