# Generated by Django 2.0.13 on 2019-04-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0131_landingpageicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_rides_view',
            field=models.CharField(blank=True, choices=[('calendar', 'Kalendář'), ('table', 'Tabulka')], default=None, max_length=16, null=True, verbose_name='Defaultní předvolba vyplňování jízd'),
        ),
    ]
