# Generated by Django 2.0.9 on 2019-04-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0132_userprofile_default_rides_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='commutemode',
            name='add_command',
            field=models.TextField(default='', verbose_name='Tooltip command for adding trip. Use {{distance}} to insert distance.'),
        ),
        migrations.AddField(
            model_name='commutemode',
            name='add_command_cs',
            field=models.TextField(default='', null=True, verbose_name='Tooltip command for adding trip. Use {{distance}} to insert distance.'),
        ),
        migrations.AddField(
            model_name='commutemode',
            name='add_command_dsnkcs',
            field=models.TextField(default='', null=True, verbose_name='Tooltip command for adding trip. Use {{distance}} to insert distance.'),
        ),
        migrations.AddField(
            model_name='commutemode',
            name='add_command_en',
            field=models.TextField(default='', null=True, verbose_name='Tooltip command for adding trip. Use {{distance}} to insert distance.'),
        ),
    ]
