# Generated by Django 2.0.13 on 2019-05-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0133_auto_20190429_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='commutemode',
            name='choice_description',
            field=models.TextField(blank=True, default=None, help_text='Use {{distance}} to insert distance.', null=True, verbose_name='Vysvětlivka výběru módu'),
        ),
        migrations.AddField(
            model_name='commutemode',
            name='choice_description_cs',
            field=models.TextField(blank=True, default=None, help_text='Use {{distance}} to insert distance.', null=True, verbose_name='Vysvětlivka výběru módu'),
        ),
        migrations.AddField(
            model_name='commutemode',
            name='choice_description_dsnkcs',
            field=models.TextField(blank=True, default=None, help_text='Use {{distance}} to insert distance.', null=True, verbose_name='Vysvětlivka výběru módu'),
        ),
        migrations.AddField(
            model_name='commutemode',
            name='choice_description_en',
            field=models.TextField(blank=True, default=None, help_text='Use {{distance}} to insert distance.', null=True, verbose_name='Vysvětlivka výběru módu'),
        ),
        migrations.AlterField(
            model_name='commutemode',
            name='add_command',
            field=models.TextField(default='', help_text='Use {{distance}} to insert distance and {{direction}} for direction.', verbose_name='Tooltip command for adding trip.'),
        ),
        migrations.AlterField(
            model_name='commutemode',
            name='add_command_cs',
            field=models.TextField(default='', help_text='Use {{distance}} to insert distance and {{direction}} for direction.', null=True, verbose_name='Tooltip command for adding trip.'),
        ),
        migrations.AlterField(
            model_name='commutemode',
            name='add_command_dsnkcs',
            field=models.TextField(default='', help_text='Use {{distance}} to insert distance and {{direction}} for direction.', null=True, verbose_name='Tooltip command for adding trip.'),
        ),
        migrations.AlterField(
            model_name='commutemode',
            name='add_command_en',
            field=models.TextField(default='', help_text='Use {{distance}} to insert distance and {{direction}} for direction.', null=True, verbose_name='Tooltip command for adding trip.'),
        ),
    ]
