# Generated by Django 2.0.13 on 2019-05-23 12:17

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0134_auto_20190502_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
