# Generated by Django 2.0.13 on 2019-08-02 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price_level', '0002_auto_20190802_1935'),
        ('dpnk', '0137_campaign_city_in_campaign_diploma_sandwich_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='award_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='price_level.AwardLevel'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company_pais_benefitial_fee',
            field=models.BooleanField(default=False, verbose_name='ZAVRHOVANÝ: Moje organizace si přeje podpořit Auto*Mat a zaplatit benefiční startovné.'),
        ),
    ]
