# Generated by Django 2.0.13 on 2019-08-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0137_campaign_city_in_campaign_diploma_sandwich_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigntype',
            name='name_cs',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='Jméno typu kampaně'),
        ),
        migrations.AddField(
            model_name='campaigntype',
            name='name_dsnkcs',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='Jméno typu kampaně'),
        ),
        migrations.AddField(
            model_name='campaigntype',
            name='name_en',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='Jméno typu kampaně'),
        ),
    ]
