# Generated by Django 2.2.7 on 2019-12-04 17:32

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpnk', '0141_auto_20191126_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityincampaigndiplomafield',
            name='fill_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='cityincampaigndiplomafield',
            name='stroke_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='diplomafield',
            name='fill_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='diplomafield',
            name='stroke_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='teamdiplomafield',
            name='fill_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='teamdiplomafield',
            name='stroke_color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
    ]
