# Generated by Django 2.0.3 on 2018-05-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stravasync', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stravaaccount',
            options={'verbose_name': 'Účet Strava', 'verbose_name_plural': 'Účty Strava'},
        ),
        migrations.AddField(
            model_name='stravaaccount',
            name='errors',
            field=models.TextField(blank=True, default=''),
        ),
    ]
