# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-26 22:35
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PSC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality_name', models.CharField(max_length=255, verbose_name='Název obce')),
                ('municipality_part_name', models.CharField(max_length=255, verbose_name='Název části obce')),
                ('district_name', models.CharField(max_length=255, verbose_name='Název okresu')),
                ('psc', models.IntegerField(help_text='Např.: „130 00“', validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(10000)], verbose_name='PSČ')),
                ('post_name', models.CharField(max_length=255, verbose_name='Název pošty')),
                ('code', models.IntegerField(verbose_name='Kód')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psc_create', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psc_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'Poštovní směrovací číslo',
                'verbose_name_plural': 'Poštovní směrovací čísla',
            },
        ),
    ]
