from datetime import date

from model_mommy import mommy


class Competitions:
    def __init__(self, cities, campaigns, companies, commute_modes, **kwargs):
        self.individual_frequency_C2010 = mommy.make(  # pk=12
            'dpnk.Competition',
            campaign=campaigns.c2010,
            city=[],
            company=companies.basic,
            competitor_type="single_user",
            date_from=date(2010, 11, 1),
            date_to=date(2010, 11, 15),
            entry_after_beginning_days=7,
            is_public=True,
            name="Pravidelnost jednotlivců",
            public_answers=False,
            rules=None,
            sex=None,
            slug="pravidelnost-jednotlivcu",
            competition_type="frequency",
            minimum_rides_base=23,
            url="http://www.dopracenakole.net/url/",
            commute_modes=[commute_modes.bicycle, commute_modes.by_foot],
        )
        self.team_frequency_c2010 = mommy.make(  # pk=3
            'dpnk.Competition',
            campaign=campaigns.c2010,
            city=[],
            company=None,
            competitor_type="team",
            date_from=date(2010, 11, 1),
            date_to=date(2010, 11, 15),
            entry_after_beginning_days=7,
            is_public=True,
            name="Pravidelnost týmů",
            public_answers=False,
            rules=None,
            sex=None,
            slug="FQ-LB",
            competition_type="frequency",
            minimum_rides_base=23,
            url="http://www.dopracenakole.net/url/",
            commute_modes=[commute_modes.bicycle, commute_modes.by_foot],
        )

        self.questionnaire = mommy.make(  # was pk=4
            "dpnk.competition",
            campaign=campaigns.c2010,
            city=[],
            company=None,
            competitor_type="single_user",
            date_from=date(2010, 11, 1),
            date_to=date(2010, 12, 2),
            entry_after_beginning_days=7,
            is_public=True,
            name="Dotazník",
            public_answers=True,
            rules=None,
            sex=None,
            slug="quest",
            competition_type="questionnaire",
            url="http://www.dopracenakole.net/url/",
        )

        self.team_questionnaire = mommy.make(  # was pk=13
            "dpnk.competition",
            campaign=campaigns.c2010,
            city=[cities.city],
            company=None,
            competitor_type="team",
            date_from=date(2010, 11, 1),
            date_to=date(2010, 12, 2),
            entry_after_beginning_days=7,
            is_public=True,
            name="Dotazník týmů",
            public_answers=True,
            rules=None,
            sex=None,
            slug="team-questionnaire",
            competition_type="questionnaire",
            url="http://www.dopracenakole.net/url/",
        )

        self.competition_mens_performance = mommy.make(  # was pk=5
            "dpnk.competition",
            campaign=campaigns.c2010,
            city=[cities.city],
            company=None,
            competitor_type="single_user",
            date_from=date(2010, 11, 1),
            date_to=date(2010, 12, 30),
            entry_after_beginning_days=7,
            is_public=True,
            name="Výkonnost",
            public_answers=False,
            rules=None,
            sex="male",
            slug="vykonnost",
            competition_type="length",
            url="http://www.dopracenakole.net/url/",
            commute_modes=[commute_modes.bicycle, commute_modes.by_foot],
        )

        self.competition_team_performance = mommy.make(  # was pk=9
            "dpnk.competition",
            campaign=campaigns.c2010,
            city=[cities.city],
            company=None,
            competitor_type="team",
            date_from=date(2010, 11, 1),
            date_to=date(2010, 12, 30),
            entry_after_beginning_days=7,
            is_public=True,
            name="Výkonnost týmů",
            public_answers=False,
            rules=None,
            sex="male",
            slug="vykonnost-tymu",
            competition_type="length",
            url="http://www.dopracenakole.net/url/",
            commute_modes=[commute_modes.bicycle, commute_modes.by_foot],
        )

        self.city_performance = mommy.make(  # was pk=6
            "dpnk.competition",
            campaign=campaigns.c2010,
            city=[cities.city],
            company=None,
            competitor_type="single_user",
            date_from=date(2010, 11, 1),
            date_to=date(2010, 12, 30),
            entry_after_beginning_days=7,
            is_public=True,
            name="Výkonnost ve městě",
            public_answers=False,
            rules="Competition vykonnostr rules",
            sex=None,
            slug="vykonnost-mesto",
            competition_type="length",
            url="http://www.dopracenakole.net/url/",
            commute_modes=[commute_modes.bicycle, commute_modes.by_foot],
        )

        self.company_performance = mommy.make(  # was pk=8
            "dpnk.competition",
            campaign=campaigns.c2010,
            city=[cities.city],
            company=None,
            competitor_type="company",
            date_from=date(2010, 11, 1),
            date_to=date(2010, 12, 30),
            entry_after_beginning_days=7,
            is_public=True,
            name="Výkonnost společností",
            public_answers=False,
            rules="Competition rules",
            sex=None,
            slug="vykonnost-spolecnosti",
            competition_type="length",
            url="http://www.dopracenakole.net/url/",
            commute_modes=[commute_modes.bicycle, commute_modes.by_foot],
        )

        self.company_regularity = mommy.make(  # was pk=10
            "dpnk.competition",
            campaign=campaigns.c2010,
            city=[cities.city],
            company=companies.basic,
            competitor_type="company",
            date_from=date(2010, 11, 1),
            date_to=date(2010, 12, 30),
            entry_after_beginning_days=7,
            is_public=True,
            name="Pravidelnost společností",
            public_answers=False,
            rules="Competition rules",
            sex=None,
            slug="pravidelnost-spolecnosti",
            competition_type="frequency",
            url="http://www.dopracenakole.net/url/",
            commute_modes=[commute_modes.bicycle, commute_modes.by_foot],
        )

        self.company_questionnaire = mommy.make(  # was pk=11
            "dpnk.competition",
            campaign=campaigns.c2010,
            city=[],
            company=None,
            competitor_type="company",
            date_from=date(2010, 11, 1),
            date_to=date(2010, 12, 30),
            entry_after_beginning_days=7,
            is_public=True,
            name="Dotazník společností",
            public_answers=False,
            rules="Competition rules",
            sex=None,
            slug="dotaznik-spolecnosti",
            competition_type="questionnaire",
            url="http://www.dopracenakole.net/url/",
        )
        self.fa_company_regularity = mommy.make(  # was pk=7
            "dpnk.competition",
            campaign=campaigns.c2010,
            city=[],
            company=companies.basic,
            competitor_type="team",
            date_from=date(2013, 5, 1),
            date_to=date(2013, 6, 2),
            entry_after_beginning_days=7,
            is_public=True,
            name="Pravidelnost společnosti",
            public_answers=False,
            rules=None,
            sex=None,
            slug="FA-testing-campaign-pravidelnost-spolecnosti",
            competition_type="frequency",
            url="http://www.dopracenakole.net/url/",
        )
