from model_mommy import mommy


class Users:
    def __init__(self, groups, cities, companies, campaigns, **kwargs):
        self.user = mommy.make(  # was pk = 1128
            "auth.user",
            date_joined = "2015-11-12T18:18:10",
            email = "test@test.cz",
            first_name = "Testing",
            groups = [groups.cykloservis_group],
            is_active = True,
            is_staff = True,
            is_superuser = True,
            last_login = "2015-11-12T18:53:35.982",
            last_name = "User 1",
            password = "md5$XtL9Iyaj7sqm$2848d5685e6022230846161a66cc30e4",
            user_permissions = [],
            username = "test",
        )
        self.userprofile = mommy.make(  # was pk = 1117
            "dpnk.userprofile",
            administrated_cities = [],
            language = "cs",
            mailing_hash = False,
            mailing_id = "",
            nickname = "",
            note = "",
            sex = "male",
            telephone = "",
            mailing_opt_in = True,
            ecc_password = "secret",
            ecc_email = "email1128@dopracenakole.cz",
            user = self.user,
        )

        self.local_organizer_user = mommy.make(  # was pk=2
            "auth.user",
            date_joined = "2015-11-12T18:16:03.886",
            email = "local_admin@auto-mat.cz",
            first_name = "",
            groups = [groups.local_organizer_group],
            is_active = True,
            is_staff = True,
            is_superuser = False,
            last_login = "2015-11-12T18:35:38.186",
            last_name = "",
            password = "md5$XtL9Iyaj7sqm$2848d5685e6022230846161a66cc30e4",
            user_permissions = [],
            username = "local_admin",
        )
        self.local_organizer_user_userprofile = mommy.make(  # was pk=2
            "dpnk.userprofile",
            administrated_cities = [cities.city],
            language = "cs",
            mailing_hash = None,
            mailing_id = "",
            nickname = "",
            note = "",
            sex = "male",
            telephone = "",
            ecc_password = "secret",
            ecc_email = "email2@dopracenakole.cz",
            user = self.local_organizer_user,
        )

        self.admin_user = mommy.make(  # was pk = 1027
            "auth.user",
            date_joined = "2015-11-12T18:16:03.886",
            email = "admin@auto-mat.cz",
            first_name = "",
            groups = [],
            is_active = True,
            is_staff = True,
            is_superuser = True,
            last_login = "2015-11-12T18:35:38.186",
            last_name = "",
            password = "md5$XtL9Iyaj7sqm$2848d5685e6022230846161a66cc30e4",
            user_permissions = [],
            username = "admin",
        )

        self.user2 = mommy.make(  # was pk=1031
            "auth.user",
            date_joined = "2015-11-12T18:18:10",
            email = "test2@test.cz",
            first_name = "Testing",
            groups = [],
            is_active = True,
            is_staff = False,
            is_superuser = False,
            last_login = "2015-11-12T18:53:35.982",
            last_name = "User",
            password = "md5$XtL9Iyaj7sqm$2848d5685e6022230846161a66cc30e4",
            user_permissions = [],
            username = "test1",
        )
        self.user2_userprofile = mommy.make(  # was pk=1017
            "dpnk.userprofile",
            administrated_cities = [],
            language = "cs",
            mailing_hash = None,
            mailing_id = "",
            nickname = "Nick",
            note = "",
            sex = "male",
            telephone = "",
            ecc_password = "secret",
            ecc_email = "email1031@dopracenakole.cz",
            user = self.user2,
        )

        self.registered_user = mommy.make(  # was pk=2128
            "auth.user",
            date_joined = "2015-11-12T18:18:10",
            email = "test-registered@test.cz",
            first_name = "Registered",
            groups = [],
            is_active = True,
            is_staff = False,
            is_superuser = False,
            last_login = "2015-11-12T18:53:35.982",
            last_name = "User 1",
            password = "md5$XtL9Iyaj7sqm$2848d5685e6022230846161a66cc30e4",
            user_permissions = [],
            username = "test-registered",
        )
        self.registered_user_userprofile = mommy.make(  # was pk=2117
            "dpnk.userprofile",
            administrated_cities = [],
            language = "cs",
            mailing_hash = None,
            mailing_id = "",
            nickname = "",
            note = "",
            sex = "male",
            telephone = "",
            ecc_password = "secret",
            ecc_email = "email2117@dopracenakole.cz",
            user = self.registered_user,
        )

        self.user_without_userattendance = mommy.make(  # was pk=1041
            "auth.user",
            date_joined = "2015-11-12T18:18:10",
            email = "test_wa@email.cz",
            first_name = "Null",
            groups = [],
            is_active = True,
            is_staff = False,
            is_superuser = False,
            last_login = "2015-11-12T18:53:35.982",
            last_name = "User",
            password = "md5$XtL9Iyaj7sqm$2848d5685e6022230846161a66cc30e4",
            user_permissions = [],
            username = "user_without_attendance",
        )
        self.user_without_userattendance_userprofile = mommy.make(  # was pk=1026
            "dpnk.userprofile",
            administrated_cities = [],
            language = "cs",
            mailing_hash = None,
            mailing_id = "",
            nickname = None,
            note = None,
            sex = "unknown",
            telephone = "",
            ecc_password = "secret",
            ecc_email = "email1041@dopracenakole.cz",
            user = self.user_without_userattendance,
        )

        self.unapproved_user = mommy.make(  # was pk=5
            "auth.user",
            date_joined = "2015-11-12T18:18:10",
            email = "unapproved@email.cz",
            first_name = "Unapproved",
            groups = [],
            is_active = True,
            is_staff = False,
            is_superuser = False,
            last_login = "2015-11-12T18:53:35.982",
            last_name = "User",
            password = "md5$XtL9Iyaj7sqm$2848d5685e6022230846161a66cc30e4",
            user_permissions = [],
            username = "unapproved_user",
        )
        self.unapproved_user_userprofile = mommy.make(  # was pk=5
            "dpnk.userprofile",
            administrated_cities = [],
            language = "cs",
            mailing_hash = None,
            mailing_id = "",
            nickname = None,
            note = None,
            sex = "male",
            telephone = "",
            ecc_password = "secret",
            ecc_email = "email5@dopracenakole.cz",
            user = self.unapproved_user,
        )

        self.user_without_team = mommy.make(  # was pk=3
            "auth.user",
            date_joined = "2015-11-12T18:18:10",
            email = "without_team@email.cz",
            first_name = "Null",
            groups = [],
            is_active = True,
            is_staff = False,
            is_superuser = False,
            last_login = "2015-11-12T18:53:35.982",
            last_name = "User",
            password = "md5$XtL9Iyaj7sqm$2848d5685e6022230846161a66cc30e4",
            user_permissions = [],
            username = "without_team",
        )
        self.user_without_team_userprofile = mommy.make(  # was pk=3
            "dpnk.userprofile",
            administrated_cities = [],
            language = "en",
            mailing_hash = None,
            mailing_id = "",
            nickname = None,
            note = None,
            sex = "female",
            telephone = "",
            ecc_password = "secret",
            ecc_email = "email3@dopracenakole.cz",
            user = self.user_without_team,
        )

        self.null_user = mommy.make(  # was pk=1030
            "auth.user",
            date_joined = "2015-11-12T18:18:10",
            email = "test@email.cz",
            first_name = "Null",
            groups = [],
            is_active = True,
            is_staff = False,
            is_superuser = False,
            last_login = "2015-11-12T18:53:35.982",
            last_name = "User",
            password = "md5$XtL9Iyaj7sqm$2848d5685e6022230846161a66cc30e4",
            user_permissions = [],
            username = "null_user",
        )
        self.null_userprofile = mommy.make(  # was pk=1016
            "dpnk.userprofile",
            administrated_cities = [],
            language = "cs",
            mailing_hash = None,
            mailing_id = "",
            nickname = None,
            note = None,
            sex = "unknown",
            telephone = "",
            ecc_password = "secret",
            ecc_email = "email1030@dopracenakole.cz",
            user = self.null_user,
        )
